;; gorilla-repl.fileformat = 1

;; **
;;; # CIM Portfolio
;; **

;; **
;;; ### Required packages
;; **

;; @@
(ns cim_portfolio.portfolio
  (:require [cim_portfolio.util :as util]
            [cim_portfolio.yfinanceclient :as client]
            [cim_portfolio.plot :as plot]
            [clojure.math :as math]
            ))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-nil'>nil</span>","value":"nil"}
;; <=

;; **
;;; ### Portfolio Analysis Helper Functions
;; **

;; @@
;; Computes arithmetic, log, and cumulative return for a given list of prices
(defn calculate-returns [prices]
  (let [price-changes (map #(double (/ (second %) (first %))) (partition 2 1 prices))
        arithmetic-returns (mapv #(- % 1.0) price-changes)
        log-returns (mapv #(Math/log %) price-changes)
        cumulative-log-return (reduce + log-returns)]
    {
     :cumulative-return cumulative-log-return
     :arithmetic-returns arithmetic-returns
     :log-returns log-returns
     }))

;; Variation of the above function - additionally associates the returns with their corresponding date
(defn calculate-returns-with-corresponding-date [prices dates]
  (let [price-changes (map #(double (/ (second %) (first %))) (partition 2 1 prices))
        arithmetic-returns (mapv #(- % 1.0) price-changes)
        log-returns (mapv #(Math/log %) price-changes)
        cumulative-log-return (reduce + log-returns)]
    {
     :cumulative-return cumulative-log-return
     :arithmetic-returns (util/sort-map-by-date (zipmap (rest dates) arithmetic-returns))
     :log-returns (util/sort-map-by-date (zipmap (rest dates) log-returns))
     }))

;; Calculates portfolio return - accepts map {:stock cash-invested} and stock-performance generated by calculate-returns
(defn calculate-portfolio-return [cash-invested returns]
  (let [total-investment (apply + (vals cash-invested))]
    (->> cash-invested
         (map (fn [[security invested]]
                (let [weight (/ invested total-investment)
                      return (:cumulative-return (get returns security))]
                  (* weight return))))
         (apply +))))

;; Calculates cumulative return UP TILL a given date
(defn get-cumulative-return-till-given-date [cumulative-returns date]
  (util/sum-up-to-key date cumulative-returns)
)

;; Only calculates portfolio return up till a given date
(defn calculate-portfolio-return-for-given-date [cash-invested returns date]
  (let [total-investment (apply + (vals cash-invested))]
    (->> cash-invested
         (map (fn [[security invested]]
                (let [weight (/ invested total-investment)
                      return (get-cumulative-return-till-given-date (:log-returns (get returns security)) date)
                     ]
                  (* weight return))))
         (apply +))))

; Calculates the annualized return of the portfolio (accepts the starting value, ending value of portfolio, the start and end date)
(defn calculate-annualized-return [starting-value ending-value start-date end-date]
  (let [return (/ (- ending-value starting-value) starting-value)
        number-of-days (util/number-of-days-between start-date end-date)
       ]
    (- (math/pow (+ 1 return) (/ 365 number-of-days)) 1)
  )
)

; Calculates the volatility of a given list of prices (expected input: portfolio value list)
(defn volatility [prices]
  (let [daily-returns (:arithmetic-returns (calculate-returns prices))
        volatility (* 100 (util/std-dev daily-returns))
       ]
    volatility
  )
)

; Calculates the volatility for a given sliding window-size
(defn rolling-volatility [prices window-size]
  (let [returns (:arithmetic-returns (calculate-returns prices))]
    (->> returns
         (partition window-size 1)
         (map util/std-dev)
      	 (map #(* 100 %))
    )
  )
)
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/rolling-volatility</span>","value":"#'cim_portfolio.portfolio/rolling-volatility"}
;; <=

;; @@
(def test-prices [100 105 110 103 108 115])

(println test-prices)

(:arithmetic-returns (calculate-returns test-prices)) ;; Daily returns (as percentage of change)

(rolling-volatility test-prices 3)
;; @@
;; ->
;;; [100 105 110 103 108 115]
;;; 
;; <-
;; =>
;;; {"type":"list-like","open":"<span class='clj-lazy-seq'>(</span>","close":"<span class='clj-lazy-seq'>)</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-double'>6.493157758793351</span>","value":"6.493157758793351"},{"type":"html","content":"<span class='clj-double'>6.450191958030683</span>","value":"6.450191958030683"},{"type":"html","content":"<span class='clj-double'>6.993904375922838</span>","value":"6.993904375922838"}],"value":"(6.493157758793351 6.450191958030683 6.993904375922838)"}
;; <=

;; @@
(calculate-returns test-prices)
;; @@
;; =>
;;; {"type":"list-like","open":"<span class='clj-map'>{</span>","close":"<span class='clj-map'>}</span>","separator":", ","items":[{"type":"list-like","open":"","close":"","separator":" ","items":[{"type":"html","content":"<span class='clj-keyword'>:cumulative-return</span>","value":":cumulative-return"},{"type":"html","content":"<span class='clj-double'>0.1397619423751591</span>","value":"0.1397619423751591"}],"value":"[:cumulative-return 0.1397619423751591]"},{"type":"list-like","open":"","close":"","separator":" ","items":[{"type":"html","content":"<span class='clj-keyword'>:arithmetic-returns</span>","value":":arithmetic-returns"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-double'>0.050000000000000044</span>","value":"0.050000000000000044"},{"type":"html","content":"<span class='clj-double'>0.047619047619047894</span>","value":"0.047619047619047894"},{"type":"html","content":"<span class='clj-double'>-0.0636363636363636</span>","value":"-0.0636363636363636"},{"type":"html","content":"<span class='clj-double'>0.048543689320388106</span>","value":"0.048543689320388106"},{"type":"html","content":"<span class='clj-double'>0.0648148148148151</span>","value":"0.0648148148148151"}],"value":"[0.050000000000000044 0.047619047619047894 -0.0636363636363636 0.048543689320388106 0.0648148148148151]"}],"value":"[:arithmetic-returns [0.050000000000000044 0.047619047619047894 -0.0636363636363636 0.048543689320388106 0.0648148148148151]]"},{"type":"list-like","open":"","close":"","separator":" ","items":[{"type":"html","content":"<span class='clj-keyword'>:log-returns</span>","value":":log-returns"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-double'>0.04879016416943205</span>","value":"0.04879016416943205"},{"type":"html","content":"<span class='clj-double'>0.04652001563489312</span>","value":"0.04652001563489312"},{"type":"html","content":"<span class='clj-double'>-0.06575137756278042</span>","value":"-0.06575137756278042"},{"type":"html","content":"<span class='clj-double'>0.04740223889458369</span>","value":"0.04740223889458369"},{"type":"html","content":"<span class='clj-double'>0.06280090123903065</span>","value":"0.06280090123903065"}],"value":"[0.04879016416943205 0.04652001563489312 -0.06575137756278042 0.04740223889458369 0.06280090123903065]"}],"value":"[:log-returns [0.04879016416943205 0.04652001563489312 -0.06575137756278042 0.04740223889458369 0.06280090123903065]]"}],"value":"{:cumulative-return 0.1397619423751591, :arithmetic-returns [0.050000000000000044 0.047619047619047894 -0.0636363636363636 0.048543689320388106 0.0648148148148151], :log-returns [0.04879016416943205 0.04652001563489312 -0.06575137756278042 0.04740223889458369 0.06280090123903065]}"}
;; <=

;; @@
(calculate-annualized-return 2000 2500 "2023-10-16" "2024-04-27")
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-double'>0.5217057952294997</span>","value":"0.5217057952294997"}
;; <=

;; **
;;; ### YFinance API
;; **

;; @@
(client/get-ticker-price-all "NVDA" "2025-01-15")
;; @@
;; =>
;;; {"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-16&quot;</span>","value":"\"2025-01-16\""},{"type":"html","content":"<span class='clj-double'>138.6399993896</span>","value":"138.6399993896"},{"type":"html","content":"<span class='clj-double'>133.5700073242</span>","value":"133.5700073242"}],"value":"[\"2025-01-16\" 138.6399993896 133.5700073242]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-17&quot;</span>","value":"\"2025-01-17\""},{"type":"html","content":"<span class='clj-double'>136.6900024414</span>","value":"136.6900024414"},{"type":"html","content":"<span class='clj-double'>137.7100067139</span>","value":"137.7100067139"}],"value":"[\"2025-01-17\" 136.6900024414 137.7100067139]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-21&quot;</span>","value":"\"2025-01-21\""},{"type":"html","content":"<span class='clj-double'>139.1600036621</span>","value":"139.1600036621"},{"type":"html","content":"<span class='clj-double'>140.8300018311</span>","value":"140.8300018311"}],"value":"[\"2025-01-21\" 139.1600036621 140.8300018311]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-22&quot;</span>","value":"\"2025-01-22\""},{"type":"html","content":"<span class='clj-double'>144.6600036621</span>","value":"144.6600036621"},{"type":"html","content":"<span class='clj-double'>147.0700073242</span>","value":"147.0700073242"}],"value":"[\"2025-01-22\" 144.6600036621 147.0700073242]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-23&quot;</span>","value":"\"2025-01-23\""},{"type":"html","content":"<span class='clj-double'>145.0500030518</span>","value":"145.0500030518"},{"type":"html","content":"<span class='clj-double'>147.2200012207</span>","value":"147.2200012207"}],"value":"[\"2025-01-23\" 145.0500030518 147.2200012207]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-24&quot;</span>","value":"\"2025-01-24\""},{"type":"html","content":"<span class='clj-double'>148.3699951172</span>","value":"148.3699951172"},{"type":"html","content":"<span class='clj-double'>142.6199951172</span>","value":"142.6199951172"}],"value":"[\"2025-01-24\" 148.3699951172 142.6199951172]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-27&quot;</span>","value":"\"2025-01-27\""},{"type":"html","content":"<span class='clj-double'>124.8000030518</span>","value":"124.8000030518"},{"type":"html","content":"<span class='clj-double'>118.4199981689</span>","value":"118.4199981689"}],"value":"[\"2025-01-27\" 124.8000030518 118.4199981689]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-28&quot;</span>","value":"\"2025-01-28\""},{"type":"html","content":"<span class='clj-double'>121.8099975586</span>","value":"121.8099975586"},{"type":"html","content":"<span class='clj-double'>128.9900054932</span>","value":"128.9900054932"}],"value":"[\"2025-01-28\" 121.8099975586 128.9900054932]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-29&quot;</span>","value":"\"2025-01-29\""},{"type":"html","content":"<span class='clj-double'>126.5</span>","value":"126.5"},{"type":"html","content":"<span class='clj-double'>123.6999969482</span>","value":"123.6999969482"}],"value":"[\"2025-01-29\" 126.5 123.6999969482]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-30&quot;</span>","value":"\"2025-01-30\""},{"type":"html","content":"<span class='clj-double'>123.0999984741</span>","value":"123.0999984741"},{"type":"html","content":"<span class='clj-double'>124.6500015259</span>","value":"124.6500015259"}],"value":"[\"2025-01-30\" 123.0999984741 124.6500015259]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-01-31&quot;</span>","value":"\"2025-01-31\""},{"type":"html","content":"<span class='clj-double'>123.7799987793</span>","value":"123.7799987793"},{"type":"html","content":"<span class='clj-double'>120.0699996948</span>","value":"120.0699996948"}],"value":"[\"2025-01-31\" 123.7799987793 120.0699996948]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-03&quot;</span>","value":"\"2025-02-03\""},{"type":"html","content":"<span class='clj-double'>114.75</span>","value":"114.75"},{"type":"html","content":"<span class='clj-double'>116.6600036621</span>","value":"116.6600036621"}],"value":"[\"2025-02-03\" 114.75 116.6600036621]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-04&quot;</span>","value":"\"2025-02-04\""},{"type":"html","content":"<span class='clj-double'>116.9599990845</span>","value":"116.9599990845"},{"type":"html","content":"<span class='clj-double'>118.6500015259</span>","value":"118.6500015259"}],"value":"[\"2025-02-04\" 116.9599990845 118.6500015259]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-05&quot;</span>","value":"\"2025-02-05\""},{"type":"html","content":"<span class='clj-double'>121.7600021362</span>","value":"121.7600021362"},{"type":"html","content":"<span class='clj-double'>124.8300018311</span>","value":"124.8300018311"}],"value":"[\"2025-02-05\" 121.7600021362 124.8300018311]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-06&quot;</span>","value":"\"2025-02-06\""},{"type":"html","content":"<span class='clj-double'>127.4199981689</span>","value":"127.4199981689"},{"type":"html","content":"<span class='clj-double'>128.6799926758</span>","value":"128.6799926758"}],"value":"[\"2025-02-06\" 127.4199981689 128.6799926758]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-07&quot;</span>","value":"\"2025-02-07\""},{"type":"html","content":"<span class='clj-double'>129.2200012207</span>","value":"129.2200012207"},{"type":"html","content":"<span class='clj-double'>129.8399963379</span>","value":"129.8399963379"}],"value":"[\"2025-02-07\" 129.2200012207 129.8399963379]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-10&quot;</span>","value":"\"2025-02-10\""},{"type":"html","content":"<span class='clj-double'>130.0899963379</span>","value":"130.0899963379"},{"type":"html","content":"<span class='clj-double'>133.5700073242</span>","value":"133.5700073242"}],"value":"[\"2025-02-10\" 130.0899963379 133.5700073242]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-11&quot;</span>","value":"\"2025-02-11\""},{"type":"html","content":"<span class='clj-double'>132.5800018311</span>","value":"132.5800018311"},{"type":"html","content":"<span class='clj-double'>132.8000030518</span>","value":"132.8000030518"}],"value":"[\"2025-02-11\" 132.5800018311 132.8000030518]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-12&quot;</span>","value":"\"2025-02-12\""},{"type":"html","content":"<span class='clj-double'>130.0200042725</span>","value":"130.0200042725"},{"type":"html","content":"<span class='clj-double'>131.1399993896</span>","value":"131.1399993896"}],"value":"[\"2025-02-12\" 130.0200042725 131.1399993896]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2025-02-13&quot;</span>","value":"\"2025-02-13\""},{"type":"html","content":"<span class='clj-double'>131.5599975586</span>","value":"131.5599975586"},{"type":"html","content":"<span class='clj-double'>135.2899932861</span>","value":"135.2899932861"}],"value":"[\"2025-02-13\" 131.5599975586 135.2899932861]"}],"value":"[[\"2025-01-16\" 138.6399993896 133.5700073242] [\"2025-01-17\" 136.6900024414 137.7100067139] [\"2025-01-21\" 139.1600036621 140.8300018311] [\"2025-01-22\" 144.6600036621 147.0700073242] [\"2025-01-23\" 145.0500030518 147.2200012207] [\"2025-01-24\" 148.3699951172 142.6199951172] [\"2025-01-27\" 124.8000030518 118.4199981689] [\"2025-01-28\" 121.8099975586 128.9900054932] [\"2025-01-29\" 126.5 123.6999969482] [\"2025-01-30\" 123.0999984741 124.6500015259] [\"2025-01-31\" 123.7799987793 120.0699996948] [\"2025-02-03\" 114.75 116.6600036621] [\"2025-02-04\" 116.9599990845 118.6500015259] [\"2025-02-05\" 121.7600021362 124.8300018311] [\"2025-02-06\" 127.4199981689 128.6799926758] [\"2025-02-07\" 129.2200012207 129.8399963379] [\"2025-02-10\" 130.0899963379 133.5700073242] [\"2025-02-11\" 132.5800018311 132.8000030518] [\"2025-02-12\" 130.0200042725 131.1399993896] [\"2025-02-13\" 131.5599975586 135.2899932861]]"}
;; <=

;; **
;;; ### Portfolio Processing Section
;; **

;; @@
(defn analyze-portfolio [data]
  (loop [cash 0.0
         portfolio {}
         portfolio-value {}
         current-value 0.0
         stock-performance {}
         cash-invested {}
         cash-invested-by-date {}
         data (rest data)]
    (if (empty? data)
      [cash portfolio portfolio-value current-value cash-invested cash-invested-by-date stock-performance]
      (let [[date action amount ticker] (first data)
            ticker-prices (client/get-ticker-price-all ticker (util/parse-date date))
            executed-date (first (first ticker-prices))				; gets the date the buy/sell order is executed
            ]
        (cond
          (= action "buy")
          (if (pos? (Double. amount))
            (let [price (second (first ticker-prices))        	; Gets open price of next trading day
                  currPrice (nth (last ticker-prices) 2)		; Gets adj close price of latest day
                  prices (mapv #(nth % 2) ticker-prices)       	; Extracts the prices from ticker-prices
                  amounts (repeatedly (count prices) #(Double. amount))	; Creates a sequence of amounts matching the number of prices
                  trading-dates (mapv #(first %) ticker-prices)
                  ]
              (recur (- cash (* (Double. amount) price))
                     (assoc portfolio ticker (+ (get portfolio ticker 0) (Double. amount)))
                     (merge-with + portfolio-value (zipmap (map first ticker-prices) (map #(- % (* (Double. amount) price))(map * prices amounts)))) ; Updates portfolio-value with the calculated values
                     (+ current-value (* (Double. amount) currPrice))
                     
                     (assoc stock-performance ticker (calculate-returns-with-corresponding-date prices trading-dates))
                     (assoc cash-invested ticker (+ (get cash-invested ticker 0) (* (Double. amount) price)))
                     (assoc cash-invested-by-date executed-date (assoc cash-invested ticker (+ (get cash-invested ticker 0) (* (Double. amount) price))))
                     (rest data)))
            (recur cash portfolio portfolio-value current-value cash-invested cash-invested-by-date stock-performance (rest data)))

          (= action "sell")
          (let [price (second (first ticker-prices))
                currPrice (second (last ticker-prices))
                prices (map second ticker-prices)
                amounts (repeatedly (count prices) #(Double. amount))
                trading-dates (mapv #(first %) ticker-prices)
                ]
            (recur (+ cash (* (Double. amount) price))
                   (assoc portfolio ticker (- (get portfolio ticker 0) (Double. amount)))
                   (merge-with + portfolio-value (zipmap (map first ticker-prices) (map #(- % (* (Double. amount) price))(map * prices amounts)))) ; Updates portfolio-value with the calculated values
                   (- current-value (* (Double. amount) currPrice))
                   
                   (assoc stock-performance ticker (calculate-returns-with-corresponding-date prices trading-dates))
                   (assoc cash-invested ticker (- (get cash-invested ticker 0) (* (Double. amount) price)))
                   (assoc cash-invested-by-date executed-date (assoc cash-invested ticker (- (get cash-invested ticker 0) (* (Double. amount) price))))
                   (rest data)))
          )))))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/analyze-portfolio</span>","value":"#'cim_portfolio.portfolio/analyze-portfolio"}
;; <=

;; @@
(def portfolio-options {
                        :starting-cash 200000
                       }
)

(def view-options {
                   :show-individual-stock-performance-by-day 	false
                   :show-cumulative-portfolio-return-by-day		true
                   :show-portfolio-value-by-day					true
                  }
)
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/view-options</span>","value":"#'cim_portfolio.portfolio/view-options"}
;; <=

;; @@
;; Please enter the relative paths of 1 or more CSV files (in a list) containing your trades below:

(def input-files ["./examples/testPortfolio1.csv" "./examples/testPortfolio.csv"])

(let [data (util/read-multiple-csv input-files)
      [cash portfolio portfolio-value current-value cash-invested cash-invested-by-date stock-performance] (analyze-portfolio data)
      sorted-portfolio-value 	(map #(vector (first %) (+ (:starting-cash portfolio-options) (second %))) (util/sort-map-by-date portfolio-value))
      cash-invested-by-dates 	(into [] cash-invested-by-date)
      current-portfolio-value 	(+ (:starting-cash portfolio-options) (+ cash current-value))
      annualized-return 		(calculate-annualized-return (:starting-cash portfolio-options) current-portfolio-value (first (first sorted-portfolio-value)) (last (last sorted-portfolio-value)))
      cumulative-portfolio-return (calculate-portfolio-return cash-invested stock-performance)
      returns-by-date 			(zipmap (map #(first %) cash-invested-by-date)(mapv #(calculate-portfolio-return-for-given-date (second %) stock-performance (first %)) cash-invested-by-dates))
      volatility 				(volatility (map second sorted-portfolio-value))
      ]
  (def portfolio-value-by-day sorted-portfolio-value)
  
  (println "Current Portfolio Value: $" (format "%.2f" current-portfolio-value) "\n")
  
  (println "Annualized Return of portfolio:" (format "%.2f" (* annualized-return 100)) "%\n")
  (println "Volatility of portfolio:" (format "%.4f" volatility) "%\n")
  (println "Annualized volatility of portfolio:" (format "%.4f" (* (Math/sqrt 252) volatility)) "%\n")
  (println "Cash On Hand (excluding value of portfolio): $" (format "%.2f"(+ (:starting-cash portfolio-options) cash)) "\n")
  (println "Portfolio (units held of each stock):" portfolio "\n")
  (println "Cash invested in each stock: " cash-invested "\n")
  (println "Cumulative Portfolio Return: " cumulative-portfolio-return "\n")
  
  (println "----------------------------------")
  (if (:show-cumulative-portfolio-return-by-day view-options) (println "Portfolio Return by date: \n" returns-by-date))
  (println "----------------------------------\n")
  
  (println "----------------------------------")
  (println "Portfolio Value Day-by-Day: ")
  (if (:show-portfolio-value-by-day view-options) 
    (run! println (map #(vector (first %) (format "%.2f" (second %))) sorted-portfolio-value))
    (println "Omitting...")
  )
  (println "----------------------------------\n")
  
  (println "----------------------------------")
  (println "Individual Stock Performance: ")
  (if (:show-individual-stock-performance-by-day view-options) 
    (clojure.pprint/pprint stock-performance)
    (println "Omitting...")
  )
  (println "----------------------------------\n")
)
;; @@
;; ->
;;; Current Portfolio Value: $ 231206.26 
;;; 
;;; Annualized Return of portfolio: 11.48 %
;;; 
;;; Volatility of portfolio: 0.5050 %
;;; 
;;; Annualized volatility of portfolio: 8.0169 %
;;; 
;;; Cash On Hand (excluding value of portfolio): $ 66643.17 
;;; 
;;; Portfolio (units held of each stock): {IEF 100.0, NVDA 70.0, SHY 170.0, RSP 35.0, SPY 150.0, GOOG 50.0, TSLA -30.0, GSG 250.0, AGG 300.0} 
;;; 
;;; Cash invested in each stock:  {IEF 9070.99990845, NVDA 4817.129821775, SHY 13787.499618528002, RSP 4944.7999572755, SPY 65155.500793454994, GOOG 7172.49984741, TSLA -6015.600128175, GSG 5449.999809275, AGG 28974.00054933} 
;;; 
;;; Cumulative Portfolio Return:  0.21386919979473362 
;;; 
;;; ----------------------------------
;;; Portfolio Return by date: 
;;;  {2024-02-16 0.42013972523589616, 2024-02-26 0.36435172914177527, 2024-03-01 -0.02167997458415588, 2024-03-11 0.4749100042963619, 2023-10-16 0.28179293177570325, 2023-11-06 0.24029480219871702, 2023-12-04 0.04456941346068173}
;;; ----------------------------------
;;; 
;;; ----------------------------------
;;; Portfolio Value Day-by-Day: 
;;; [2023-10-16 198927.79]
;;; [2023-10-17 198861.51]
;;; [2023-10-18 198172.54]
;;; [2023-10-19 197701.22]
;;; [2023-10-20 197178.65]
;;; [2023-10-23 197118.03]
;;; [2023-10-24 197474.49]
;;; [2023-10-25 196747.71]
;;; [2023-10-26 196314.34]
;;; [2023-10-27 196091.21]
;;; [2023-10-30 196580.89]
;;; [2023-10-31 196857.29]
;;; [2023-11-01 197413.53]
;;; [2023-11-02 198367.47]
;;; [2023-11-03 198903.35]
;;; [2023-11-06 197948.03]
;;; [2023-11-07 198027.61]
;;; [2023-11-08 198029.08]
;;; [2023-11-09 197353.75]
;;; [2023-11-10 198471.09]
;;; [2023-11-13 198490.54]
;;; [2023-11-14 200060.74]
;;; [2023-11-15 200093.54]
;;; [2023-11-16 200094.38]
;;; [2023-11-17 200292.03]
;;; [2023-11-20 200907.83]
;;; [2023-11-21 200797.10]
;;; [2023-11-22 201024.82]
;;; [2023-11-24 200972.74]
;;; [2023-11-27 200872.17]
;;; [2023-11-28 201074.75]
;;; [2023-11-29 201172.74]
;;; [2023-11-30 201330.08]
;;; [2023-12-01 201880.19]
;;; [2023-12-04 200172.06]
;;; [2023-12-05 200338.74]
;;; [2023-12-06 200035.05]
;;; [2023-12-07 200601.44]
;;; [2023-12-08 200732.10]
;;; [2023-12-11 201039.20]
;;; [2023-12-12 201361.34]
;;; [2023-12-13 203020.16]
;;; [2023-12-14 203742.90]
;;; [2023-12-15 203518.68]
;;; [2023-12-18 203875.08]
;;; [2023-12-19 204452.05]
;;; [2023-12-20 203502.34]
;;; [2023-12-21 204246.09]
;;; [2023-12-22 204343.82]
;;; [2023-12-26 204800.41]
;;; [2023-12-27 205167.95]
;;; [2023-12-28 205031.04]
;;; [2023-12-29 204704.32]
;;; [2024-01-02 204073.23]
;;; [2024-01-03 203561.07]
;;; [2024-01-04 203134.27]
;;; [2024-01-05 203176.35]
;;; [2024-01-08 204277.02]
;;; [2024-01-09 204193.96]
;;; [2024-01-10 204490.99]
;;; [2024-01-11 204743.29]
;;; [2024-01-12 204894.68]
;;; [2024-01-16 204254.42]
;;; [2024-01-17 203692.70]
;;; [2024-01-18 204354.82]
;;; [2024-01-19 205267.49]
;;; [2024-01-22 205570.60]
;;; [2024-01-23 205710.80]
;;; [2024-01-24 205710.50]
;;; [2024-01-25 206418.75]
;;; [2024-01-26 206318.92]
;;; [2024-01-29 207046.42]
;;; [2024-01-30 207095.30]
;;; [2024-01-31 206005.15]
;;; [2024-02-01 207168.98]
;;; [2024-02-02 207432.36]
;;; [2024-02-05 206793.98]
;;; [2024-02-06 207287.69]
;;; [2024-02-07 207872.63]
;;; [2024-02-08 207874.90]
;;; [2024-02-09 208288.01]
;;; [2024-02-12 208318.74]
;;; [2024-02-13 206794.78]
;;; [2024-02-14 207629.51]
;;; [2024-02-15 208351.49]
;;; [2024-02-16 207684.84]
;;; [2024-02-20 206970.92]
;;; [2024-02-21 206748.95]
;;; [2024-02-22 209473.93]
;;; [2024-02-23 209645.53]
;;; [2024-02-26 209078.82]
;;; [2024-02-27 209255.34]
;;; [2024-02-28 208992.18]
;;; [2024-02-29 209624.48]
;;; [2024-03-01 210862.40]
;;; [2024-03-04 210717.01]
;;; [2024-03-05 209694.20]
;;; [2024-03-06 210336.82]
;;; [2024-03-07 211602.02]
;;; [2024-03-08 210892.59]
;;; [2024-03-11 210584.87]
;;; [2024-03-12 212049.28]
;;; [2024-03-13 211838.92]
;;; [2024-03-14 211085.93]
;;; [2024-03-15 210210.64]
;;; [2024-03-18 211396.56]
;;; [2024-03-19 211986.96]
;;; [2024-03-20 213099.59]
;;; [2024-03-21 213639.56]
;;; [2024-03-22 213689.82]
;;; [2024-03-25 213612.02]
;;; [2024-03-26 213602.43]
;;; [2024-03-27 214273.15]
;;; [2024-03-28 214098.92]
;;; [2024-04-01 213834.42]
;;; [2024-04-02 212789.77]
;;; [2024-04-03 212916.46]
;;; [2024-04-04 211781.95]
;;; [2024-04-05 212582.93]
;;; [2024-04-08 212658.90]
;;; [2024-04-09 212877.01]
;;; [2024-04-10 211562.07]
;;; [2024-04-11 212720.16]
;;; [2024-04-12 211409.47]
;;; [2024-04-15 209749.99]
;;; [2024-04-16 209090.86]
;;; [2024-04-17 208520.90]
;;; [2024-04-18 208043.76]
;;; [2024-04-19 206449.22]
;;; [2024-04-22 207240.50]
;;; [2024-04-23 208836.37]
;;; [2024-04-24 209143.88]
;;; [2024-04-25 208639.21]
;;; [2024-04-26 211168.76]
;;; [2024-04-29 211996.19]
;;; [2024-04-30 210110.90]
;;; [2024-05-01 209395.28]
;;; [2024-05-02 210747.79]
;;; [2024-05-03 212329.97]
;;; [2024-05-06 213707.57]
;;; [2024-05-07 213896.60]
;;; [2024-05-08 213335.61]
;;; [2024-05-09 213933.29]
;;; [2024-05-10 213891.39]
;;; [2024-05-13 213957.65]
;;; [2024-05-14 214666.45]
;;; [2024-05-15 216659.80]
;;; [2024-05-16 216400.80]
;;; [2024-05-17 216329.98]
;;; [2024-05-20 216785.16]
;;; [2024-05-21 217086.66]
;;; [2024-05-22 216876.34]
;;; [2024-05-23 216981.79]
;;; [2024-05-24 217809.24]
;;; [2024-05-28 218791.42]
;;; [2024-05-29 218026.22]
;;; [2024-05-30 217203.01]
;;; [2024-05-31 217970.08]
;;; [2024-06-03 218729.54]
;;; [2024-06-04 219051.68]
;;; [2024-06-05 220984.47]
;;; [2024-06-06 221123.36]
;;; [2024-06-07 220347.86]
;;; [2024-06-10 220814.41]
;;; [2024-06-11 221110.40]
;;; [2024-06-12 222476.48]
;;; [2024-06-13 223850.77]
;;; [2024-06-14 224163.51]
;;; [2024-06-17 224515.36]
;;; [2024-06-18 225481.56]
;;; [2024-06-20 224981.88]
;;; [2024-06-21 224091.99]
;;; [2024-06-24 223082.87]
;;; [2024-06-25 224254.78]
;;; [2024-06-26 224372.14]
;;; [2024-06-27 224665.84]
;;; [2024-06-28 224053.76]
;;; [2024-07-01 224152.69]
;;; [2024-07-02 225283.48]
;;; [2024-07-03 226985.07]
;;; [2024-07-05 228298.25]
;;; [2024-07-08 228438.28]
;;; [2024-07-09 228934.54]
;;; [2024-07-10 230777.36]
;;; [2024-07-11 229438.01]
;;; [2024-07-12 229216.77]
;;; [2024-07-15 229945.70]
;;; [2024-07-16 230256.30]
;;; [2024-07-17 227841.01]
;;; [2024-07-18 227103.41]
;;; [2024-07-19 225890.68]
;;; [2024-07-22 227435.10]
;;; [2024-07-23 227527.22]
;;; [2024-07-24 223230.59]
;;; [2024-07-25 222036.86]
;;; [2024-07-26 223403.87]
;;; [2024-07-29 223487.85]
;;; [2024-07-30 222549.82]
;;; [2024-07-31 225577.31]
;;; [2024-08-01 223760.91]
;;; [2024-08-02 221411.44]
;;; [2024-08-05 216609.66]
;;; [2024-08-06 218274.18]
;;; [2024-08-07 217248.98]
;;; [2024-08-08 219523.15]
;;; [2024-08-09 220266.21]
;;; [2024-08-12 220897.13]
;;; [2024-08-13 223374.24]
;;; [2024-08-14 224135.08]
;;; [2024-08-15 225884.59]
;;; [2024-08-16 226675.01]
;;; [2024-08-19 228489.16]
;;; [2024-08-20 228562.37]
;;; [2024-08-21 228895.71]
;;; [2024-08-22 227587.57]
;;; [2024-08-23 229102.27]
;;; [2024-08-26 228905.56]
;;; [2024-08-27 228809.91]
;;; [2024-08-28 227835.27]
;;; [2024-08-29 226811.53]
;;; [2024-08-30 227654.56]
;;; [2024-09-03 224564.09]
;;; [2024-09-04 223866.15]
;;; [2024-09-05 224260.34]
;;; [2024-09-06 222426.34]
;;; [2024-09-09 223127.88]
;;; [2024-09-10 223941.98]
;;; [2024-09-11 225983.42]
;;; [2024-09-12 227386.07]
;;; [2024-09-13 228284.44]
;;; [2024-09-16 228368.87]
;;; [2024-09-17 228386.23]
;;; [2024-09-18 227701.83]
;;; [2024-09-19 230034.14]
;;; [2024-09-20 229944.78]
;;; [2024-09-23 230138.39]
;;; [2024-09-24 231364.32]
;;; [2024-09-25 231266.67]
;;; [2024-09-26 232061.94]
;;; [2024-09-27 231778.37]
;;; [2024-09-30 231978.08]
;;; [2024-10-01 231219.81]
;;; [2024-10-02 230719.42]
;;; [2024-10-03 230880.17]
;;; [2024-10-04 231841.56]
;;; [2024-10-07 231097.50]
;;; [2024-10-08 232414.72]
;;; [2024-10-09 232854.77]
;;; [2024-10-10 232879.06]
;;; [2024-10-11 232955.47]
;;; [2024-10-14 234064.65]
;;; [2024-10-15 232827.31]
;;; [2024-10-16 233624.77]
;;; [2024-10-17 233589.50]
;;; [2024-10-18 234036.52]
;;; [2024-10-21 234114.31]
;;; [2024-10-22 234247.21]
;;; [2024-10-23 232759.02]
;;; [2024-10-24 233898.70]
;;; [2024-10-25 234378.20]
;;; [2024-10-28 234894.94]
;;; [2024-10-29 235007.53]
;;; [2024-10-30 234582.76]
;;; [2024-10-31 231974.25]
;;; [2024-11-01 232100.17]
;;; [2024-11-04 232017.56]
;;; [2024-11-05 233719.90]
;;; [2024-11-06 237840.30]
;;; [2024-11-07 239638.73]
;;; [2024-11-08 240170.79]
;;; [2024-11-11 241384.86]
;;; [2024-11-12 241007.97]
;;; [2024-11-13 240574.31]
;;; [2024-11-14 239522.86]
;;; [2024-11-15 237088.46]
;;; [2024-11-18 238343.90]
;;; [2024-11-19 239457.42]
;;; [2024-11-20 239701.32]
;;; [2024-11-21 239973.37]
;;; [2024-11-22 239552.06]
;;; [2024-11-25 240234.25]
;;; [2024-11-26 240071.02]
;;; [2024-11-27 239706.73]
;;; [2024-11-29 240616.06]
;;; [2024-12-02 241440.93]
;;; [2024-12-03 241570.05]
;;; [2024-12-04 243021.84]
;;; [2024-12-05 243043.38]
;;; [2024-12-06 243652.82]
;;; [2024-12-09 243208.40]
;;; [2024-12-10 242806.89]
;;; [2024-12-11 244868.84]
;;; [2024-12-12 244305.60]
;;; [2024-12-13 243616.20]
;;; [2024-12-16 244576.36]
;;; [2024-12-17 244813.03]
;;; [2024-12-18 240944.46]
;;; [2024-12-19 240436.34]
;;; [2024-12-20 241495.08]
;;; [2024-12-23 242845.23]
;;; [2024-12-24 244348.03]
;;; [2024-12-26 245199.28]
;;; [2024-12-27 243198.39]
;;; [2024-12-30 241330.67]
;;; [2024-12-31 240799.22]
;;; [2025-01-02 239964.86]
;;; [2025-01-03 241665.20]
;;; [2025-01-06 244388.52]
;;; [2025-01-07 241851.97]
;;; [2025-01-08 241256.73]
;;; [2025-01-10 239011.71]
;;; [2025-01-13 238422.94]
;;; [2025-01-14 239499.34]
;;; [2025-01-15 242178.17]
;;; [2025-01-16 242266.26]
;;; [2025-01-17 243624.10]
;;; [2025-01-21 245436.21]
;;; [2025-01-22 246140.33]
;;; [2025-01-23 246554.36]
;;; [2025-01-24 246079.31]
;;; [2025-01-27 240832.02]
;;; [2025-01-28 242789.04]
;;; [2025-01-29 241887.86]
;;; [2025-01-30 243245.28]
;;; [2025-01-31 242057.62]
;;; [2025-02-03 240267.08]
;;; [2025-02-04 241369.18]
;;; [2025-02-05 242139.88]
;;; [2025-02-06 242501.28]
;;; [2025-02-07 241284.63]
;;; [2025-02-10 242043.48]
;;; [2025-02-11 241671.18]
;;; [2025-02-12 240243.13]
;;; [2025-02-13 242582.92]
;;; ----------------------------------
;;; 
;;; ----------------------------------
;;; Individual Stock Performance: 
;;; Omitting...
;;; ----------------------------------
;;; 
;;; 
;; <-
;; =>
;;; {"type":"html","content":"<span class='clj-nil'>nil</span>","value":"nil"}
;; <=

;; **
;;; ### Visualization
;;; 
;;; #### Portfolio Value
;; **

;; @@
(plot/list-plot (cons (:starting-cash portfolio-options) (map #(second %) portfolio-value-by-day)) :joined true :plot-size 800 :x-title "Day" :y-title "Portfolio Value (in $)" :color "#7f3b08")
;; @@
;; =>
;;; {"type":"vega","content":{"width":800,"height":494.4376,"padding":{"top":10,"left":80,"bottom":50,"right":10},"data":[{"name":"60893bb2-3a47-49e8-aae9-1d293fb11e70","values":[{"x":0,"y":200000},{"x":1,"y":198927.7941131565},{"x":2,"y":198861.51077270252},{"x":3,"y":198172.541580209},{"x":4,"y":197701.22146606148},{"x":5,"y":197178.650207521},{"x":6,"y":197118.02795410302},{"x":7,"y":197474.494323733},{"x":8,"y":196747.7062988275},{"x":9,"y":196314.3352508535},{"x":10,"y":196091.2148284865},{"x":11,"y":196580.888137817},{"x":12,"y":196857.2888946495},{"x":13,"y":197413.53477478},{"x":14,"y":198367.469558715},{"x":15,"y":198903.3545684745},{"x":16,"y":197948.0342864935},{"x":17,"y":198027.6068878225},{"x":18,"y":198029.075088502},{"x":19,"y":197353.7509727395},{"x":20,"y":198471.0941505195},{"x":21,"y":198490.5401802075},{"x":22,"y":200060.741233835},{"x":23,"y":200093.537044508},{"x":24,"y":200094.377727501},{"x":25,"y":200292.0261383065},{"x":26,"y":200907.829303715},{"x":27,"y":200797.101936343},{"x":28,"y":201024.822788248},{"x":29,"y":200972.7387428115},{"x":30,"y":200872.166519173},{"x":31,"y":201074.748191831},{"x":32,"y":201172.7444076415},{"x":33,"y":201330.078315722},{"x":34,"y":201880.192089055},{"x":35,"y":200172.056064585},{"x":36,"y":200338.739662151},{"x":37,"y":200035.050754513},{"x":38,"y":200601.4358901785},{"x":39,"y":200732.1043968085},{"x":40,"y":201039.2008018305},{"x":41,"y":201361.3350868055},{"x":42,"y":203020.160789493},{"x":43,"y":203742.8967475775},{"x":44,"y":203518.678379019},{"x":45,"y":203875.0769424065},{"x":46,"y":204452.0488738915},{"x":47,"y":203502.3415946845},{"x":48,"y":204246.09054562},{"x":49,"y":204343.82028575902},{"x":50,"y":204800.4117011755},{"x":51,"y":205167.950439415},{"x":52,"y":205031.043739294},{"x":53,"y":204704.32394024948},{"x":54,"y":204073.232707977},{"x":55,"y":203561.0724258095},{"x":56,"y":203134.269199347},{"x":57,"y":203176.348590829},{"x":58,"y":204277.0208739765},{"x":59,"y":204193.9645766945},{"x":60,"y":204490.9949493145},{"x":61,"y":204743.2912826495},{"x":62,"y":204894.67632289452},{"x":63,"y":204254.42333217402},{"x":64,"y":203692.7042388455},{"x":65,"y":204354.817981689},{"x":66,"y":205267.487697583},{"x":67,"y":205570.5981826575},{"x":68,"y":205710.7975768775},{"x":69,"y":205710.4953002955},{"x":70,"y":206418.7541770715},{"x":71,"y":206318.92086027502},{"x":72,"y":207046.4186096065},{"x":73,"y":207095.29548643},{"x":74,"y":206005.1455879015},{"x":75,"y":207168.98265835},{"x":76,"y":207432.361087787},{"x":77,"y":206793.9758491435},{"x":78,"y":207287.6930999605},{"x":79,"y":207872.6313209305},{"x":80,"y":207874.9033164645},{"x":81,"y":208288.0116653235},{"x":82,"y":208318.7423324505},{"x":83,"y":206794.7761726175},{"x":84,"y":207629.5116996555},{"x":85,"y":208351.489582035},{"x":86,"y":207684.836006148},{"x":87,"y":206970.92090604152},{"x":88,"y":206748.9544677585},{"x":89,"y":209473.934555049},{"x":90,"y":209645.5337142875},{"x":91,"y":209078.822402951},{"x":92,"y":209255.344181051},{"x":93,"y":208992.17885969148},{"x":94,"y":209624.475193003},{"x":95,"y":210862.3985099525},{"x":96,"y":210717.010955779},{"x":97,"y":209694.2006301985},{"x":98,"y":210336.816329947},{"x":99,"y":211602.02384945398},{"x":100,"y":210892.5866126995},{"x":101,"y":210584.8673057395},{"x":102,"y":212049.284343671},{"x":103,"y":211838.919944761},{"x":104,"y":211085.9303474385},{"x":105,"y":210210.6435966015},{"x":106,"y":211396.560192109},{"x":107,"y":211986.956691728},{"x":108,"y":213099.591255184},{"x":109,"y":213639.5622062685},{"x":110,"y":213689.8210906865},{"x":111,"y":213612.017288175},{"x":112,"y":213602.429561605},{"x":113,"y":214273.15179824902},{"x":114,"y":214098.9192008705},{"x":115,"y":213834.4186592045},{"x":116,"y":212789.7735214315},{"x":117,"y":212916.4576530335},{"x":118,"y":211781.949920644},{"x":119,"y":212582.928085335},{"x":120,"y":212658.89739990802},{"x":121,"y":212877.0080947595},{"x":122,"y":211562.0689200885},{"x":123,"y":212720.159664128},{"x":124,"y":211409.4685554395},{"x":125,"y":209749.99357222},{"x":126,"y":209090.8633422415},{"x":127,"y":208520.904541022},{"x":128,"y":208043.7645339835},{"x":129,"y":206449.2176246665},{"x":130,"y":207240.5035781715},{"x":131,"y":208836.368389139},{"x":132,"y":209143.883800469},{"x":133,"y":208639.2059707545},{"x":134,"y":211168.762874581},{"x":135,"y":211996.1928558375},{"x":136,"y":210110.8989715575},{"x":137,"y":209395.283145862},{"x":138,"y":210747.7878951915},{"x":139,"y":212329.9674033845},{"x":140,"y":213707.5673293895},{"x":141,"y":213896.599712353},{"x":142,"y":213335.6060027905},{"x":143,"y":213933.286266332},{"x":144,"y":213891.3928031725},{"x":145,"y":213957.654590577},{"x":146,"y":214666.4510726965},{"x":147,"y":216659.795761093},{"x":148,"y":216400.8012008725},{"x":149,"y":216329.976921091},{"x":150,"y":216785.163497936},{"x":151,"y":217086.663837438},{"x":152,"y":216876.3449096475},{"x":153,"y":216981.7884635895},{"x":154,"y":217809.2418098565},{"x":155,"y":218791.4202689955},{"x":156,"y":218026.2186050035},{"x":157,"y":217203.0135536065},{"x":158,"y":217970.0837707525},{"x":159,"y":218729.5413971015},{"x":160,"y":219051.67634960602},{"x":161,"y":220984.472732518},{"x":162,"y":221123.357887227},{"x":163,"y":220347.864818556},{"x":164,"y":220814.40694808},{"x":165,"y":221110.4021262845},{"x":166,"y":222476.4763641225},{"x":167,"y":223850.774040202},{"x":168,"y":224163.5145187165},{"x":169,"y":224515.364131909},{"x":170,"y":225481.56459806502},{"x":171,"y":224981.879158003},{"x":172,"y":224091.9942664765},{"x":173,"y":223082.8681754835},{"x":174,"y":224254.780273421},{"x":175,"y":224372.1410942155},{"x":176,"y":224665.8438873235},{"x":177,"y":224053.7555122055},{"x":178,"y":224152.69153592},{"x":179,"y":225283.478260042},{"x":180,"y":226985.069332104},{"x":181,"y":228298.25336454602},{"x":182,"y":228438.2802963105},{"x":183,"y":228934.5385169735},{"x":184,"y":230777.361869798},{"x":185,"y":229438.0132675125},{"x":186,"y":229216.7705535765},{"x":187,"y":229945.6987571605},{"x":188,"y":230256.30201338348},{"x":189,"y":227841.00788113102},{"x":190,"y":227103.4130286855},{"x":191,"y":225890.679111463},{"x":192,"y":227435.09809491748},{"x":193,"y":227527.222537985},{"x":194,"y":223230.5912017595},{"x":195,"y":222036.864242504},{"x":196,"y":223403.87006756398},{"x":197,"y":223487.85125729349},{"x":198,"y":222549.8225211735},{"x":199,"y":225577.308139778},{"x":200,"y":223760.9089088325},{"x":201,"y":221411.4437293865},{"x":202,"y":216609.6567534965},{"x":203,"y":218274.1766547875},{"x":204,"y":217248.9762496915},{"x":205,"y":219523.1471252095},{"x":206,"y":220266.2115860015},{"x":207,"y":220897.133827179},{"x":208,"y":223374.2358970395},{"x":209,"y":224135.0770568425},{"x":210,"y":225884.5863914155},{"x":211,"y":226675.013771029},{"x":212,"y":228489.1572952135},{"x":213,"y":228562.3737525745},{"x":214,"y":228895.71252821852},{"x":215,"y":227587.5681113855},{"x":216,"y":229102.27090830798},{"x":217,"y":228905.5615996925},{"x":218,"y":228809.90947721002},{"x":219,"y":227835.2689742765},{"x":220,"y":226811.5306663425},{"x":221,"y":227654.5632552825},{"x":222,"y":224564.0935897455},{"x":223,"y":223866.154880488},{"x":224,"y":224260.3366661045},{"x":225,"y":222426.34246826402},{"x":226,"y":223127.8765296725},{"x":227,"y":223941.9772338655},{"x":228,"y":225983.423500051},{"x":229,"y":227386.0654067855},{"x":230,"y":228284.438056919},{"x":231,"y":228368.872737871},{"x":232,"y":228386.2299537645},{"x":233,"y":227701.830406172},{"x":234,"y":230034.142932886},{"x":235,"y":229944.7773551725},{"x":236,"y":230138.3947372295},{"x":237,"y":231364.317932113},{"x":238,"y":231266.6678809975},{"x":239,"y":232061.9403648245},{"x":240,"y":231778.365993481},{"x":241,"y":231978.0772018175},{"x":242,"y":231219.8146438645},{"x":243,"y":230719.416656495},{"x":244,"y":230880.170688623},{"x":245,"y":231841.55820843249},{"x":246,"y":231097.497692097},{"x":247,"y":232414.724826799},{"x":248,"y":232854.765586851},{"x":249,"y":232879.0609741125},{"x":250,"y":232955.474586467},{"x":251,"y":234064.6536445475},{"x":252,"y":232827.308578456},{"x":253,"y":233624.769992794},{"x":254,"y":233589.5029067705},{"x":255,"y":234036.51655195502},{"x":256,"y":234114.3051719505},{"x":257,"y":234247.21010207452},{"x":258,"y":232759.02112959352},{"x":259,"y":233898.69514461598},{"x":260,"y":234378.1956481785},{"x":261,"y":234894.9417495345},{"x":262,"y":235007.529106131},{"x":263,"y":234582.76254651},{"x":264,"y":231974.2527008155},{"x":265,"y":232100.174217197},{"x":266,"y":232017.5571441405},{"x":267,"y":233719.9002074905},{"x":268,"y":237840.29542918748},{"x":269,"y":239638.7348174965},{"x":270,"y":240170.78592298698},{"x":271,"y":241384.86026760697},{"x":272,"y":241007.97464367998},{"x":273,"y":240574.3055724955},{"x":274,"y":239522.8641318995},{"x":275,"y":237088.4553527525},{"x":276,"y":238343.89791485848},{"x":277,"y":239457.4205016885},{"x":278,"y":239701.322784386},{"x":279,"y":239973.37356564},{"x":280,"y":239552.0639037735},{"x":281,"y":240234.25193783653},{"x":282,"y":240071.0241889725},{"x":283,"y":239706.731357568},{"x":284,"y":240616.0608291395},{"x":285,"y":241440.928611735},{"x":286,"y":241570.04623414698},{"x":287,"y":243021.8405914225},{"x":288,"y":243043.376197786},{"x":289,"y":243652.82417293498},{"x":290,"y":243208.40456008748},{"x":291,"y":242806.891231519},{"x":292,"y":244868.837547279},{"x":293,"y":244305.6034087735},{"x":294,"y":243616.19625087548},{"x":295,"y":244576.36032100697},{"x":296,"y":244813.0298041785},{"x":297,"y":240944.455814348},{"x":298,"y":240436.3371658005},{"x":299,"y":241495.076847057},{"x":300,"y":242845.23145673},{"x":301,"y":244348.02936551452},{"x":302,"y":245199.281616203},{"x":303,"y":243198.3929252455},{"x":304,"y":241330.670928935},{"x":305,"y":240799.222946144},{"x":306,"y":239964.860591877},{"x":307,"y":241665.2047729175},{"x":308,"y":244388.5189247045},{"x":309,"y":241851.9705581555},{"x":310,"y":241256.7307853605},{"x":311,"y":239011.71306609552},{"x":312,"y":238422.943057995},{"x":313,"y":239499.341583237},{"x":314,"y":242178.16839214799},{"x":315,"y":242266.258602121},{"x":316,"y":243624.09843442298},{"x":317,"y":245436.21141431452},{"x":318,"y":246140.3289413135},{"x":319,"y":246554.361419645},{"x":320,"y":246079.3128585505},{"x":321,"y":240832.0218086025},{"x":322,"y":242789.041023247},{"x":323,"y":241887.8588676145},{"x":324,"y":243245.2753066815},{"x":325,"y":242057.62161253148},{"x":326,"y":240267.08185191048},{"x":327,"y":241369.18394087},{"x":328,"y":242139.87621305598},{"x":329,"y":242501.2777328435},{"x":330,"y":241284.632072423},{"x":331,"y":242043.475894903},{"x":332,"y":241671.1778831505},{"x":333,"y":240243.1269645435},{"x":334,"y":242582.9242706335}]}],"marks":[{"type":"line","from":{"data":"60893bb2-3a47-49e8-aae9-1d293fb11e70"},"properties":{"enter":{"x":{"scale":"x","field":"data.x"},"y":{"scale":"y","field":"data.y"},"stroke":{"value":"#7f3b08"},"strokeWidth":{"value":3},"strokeOpacity":{"value":1}}}}],"scales":[{"name":"x","type":"linear","range":"width","zero":false,"domain":{"data":"60893bb2-3a47-49e8-aae9-1d293fb11e70","field":"data.x"}},{"name":"y","type":"linear","range":"height","nice":true,"zero":false,"domain":{"data":"60893bb2-3a47-49e8-aae9-1d293fb11e70","field":"data.y"}}],"axes":[{"type":"x","scale":"x","title":"Day","titleOffset":40,"grid":true},{"type":"y","scale":"y","title":"Portfolio Value (in $)","titleOffset":65,"grid":true}]},"value":"#gorilla_repl.vega.VegaView{:content {:width 800, :height 494.4376, :padding {:top 10, :left 80, :bottom 50, :right 10}, :data [{:name \"60893bb2-3a47-49e8-aae9-1d293fb11e70\", :values ({:x 0, :y 200000} {:x 1, :y 198927.7941131565} {:x 2, :y 198861.51077270252} {:x 3, :y 198172.541580209} {:x 4, :y 197701.22146606148} {:x 5, :y 197178.650207521} {:x 6, :y 197118.02795410302} {:x 7, :y 197474.494323733} {:x 8, :y 196747.7062988275} {:x 9, :y 196314.3352508535} {:x 10, :y 196091.2148284865} {:x 11, :y 196580.888137817} {:x 12, :y 196857.2888946495} {:x 13, :y 197413.53477478} {:x 14, :y 198367.469558715} {:x 15, :y 198903.3545684745} {:x 16, :y 197948.0342864935} {:x 17, :y 198027.6068878225} {:x 18, :y 198029.075088502} {:x 19, :y 197353.7509727395} {:x 20, :y 198471.0941505195} {:x 21, :y 198490.5401802075} {:x 22, :y 200060.741233835} {:x 23, :y 200093.537044508} {:x 24, :y 200094.377727501} {:x 25, :y 200292.0261383065} {:x 26, :y 200907.829303715} {:x 27, :y 200797.101936343} {:x 28, :y 201024.822788248} {:x 29, :y 200972.7387428115} {:x 30, :y 200872.166519173} {:x 31, :y 201074.748191831} {:x 32, :y 201172.7444076415} {:x 33, :y 201330.078315722} {:x 34, :y 201880.192089055} {:x 35, :y 200172.056064585} {:x 36, :y 200338.739662151} {:x 37, :y 200035.050754513} {:x 38, :y 200601.4358901785} {:x 39, :y 200732.1043968085} {:x 40, :y 201039.2008018305} {:x 41, :y 201361.3350868055} {:x 42, :y 203020.160789493} {:x 43, :y 203742.8967475775} {:x 44, :y 203518.678379019} {:x 45, :y 203875.0769424065} {:x 46, :y 204452.0488738915} {:x 47, :y 203502.3415946845} {:x 48, :y 204246.09054562} {:x 49, :y 204343.82028575902} {:x 50, :y 204800.4117011755} {:x 51, :y 205167.950439415} {:x 52, :y 205031.043739294} {:x 53, :y 204704.32394024948} {:x 54, :y 204073.232707977} {:x 55, :y 203561.0724258095} {:x 56, :y 203134.269199347} {:x 57, :y 203176.348590829} {:x 58, :y 204277.0208739765} {:x 59, :y 204193.9645766945} {:x 60, :y 204490.9949493145} {:x 61, :y 204743.2912826495} {:x 62, :y 204894.67632289452} {:x 63, :y 204254.42333217402} {:x 64, :y 203692.7042388455} {:x 65, :y 204354.817981689} {:x 66, :y 205267.487697583} {:x 67, :y 205570.5981826575} {:x 68, :y 205710.7975768775} {:x 69, :y 205710.4953002955} {:x 70, :y 206418.7541770715} {:x 71, :y 206318.92086027502} {:x 72, :y 207046.4186096065} {:x 73, :y 207095.29548643} {:x 74, :y 206005.1455879015} {:x 75, :y 207168.98265835} {:x 76, :y 207432.361087787} {:x 77, :y 206793.9758491435} {:x 78, :y 207287.6930999605} {:x 79, :y 207872.6313209305} {:x 80, :y 207874.9033164645} {:x 81, :y 208288.0116653235} {:x 82, :y 208318.7423324505} {:x 83, :y 206794.7761726175} {:x 84, :y 207629.5116996555} {:x 85, :y 208351.489582035} {:x 86, :y 207684.836006148} {:x 87, :y 206970.92090604152} {:x 88, :y 206748.9544677585} {:x 89, :y 209473.934555049} {:x 90, :y 209645.5337142875} {:x 91, :y 209078.822402951} {:x 92, :y 209255.344181051} {:x 93, :y 208992.17885969148} {:x 94, :y 209624.475193003} {:x 95, :y 210862.3985099525} {:x 96, :y 210717.010955779} {:x 97, :y 209694.2006301985} {:x 98, :y 210336.816329947} {:x 99, :y 211602.02384945398} {:x 100, :y 210892.5866126995} {:x 101, :y 210584.8673057395} {:x 102, :y 212049.284343671} {:x 103, :y 211838.919944761} {:x 104, :y 211085.9303474385} {:x 105, :y 210210.6435966015} {:x 106, :y 211396.560192109} {:x 107, :y 211986.956691728} {:x 108, :y 213099.591255184} {:x 109, :y 213639.5622062685} {:x 110, :y 213689.8210906865} {:x 111, :y 213612.017288175} {:x 112, :y 213602.429561605} {:x 113, :y 214273.15179824902} {:x 114, :y 214098.9192008705} {:x 115, :y 213834.4186592045} {:x 116, :y 212789.7735214315} {:x 117, :y 212916.4576530335} {:x 118, :y 211781.949920644} {:x 119, :y 212582.928085335} {:x 120, :y 212658.89739990802} {:x 121, :y 212877.0080947595} {:x 122, :y 211562.0689200885} {:x 123, :y 212720.159664128} {:x 124, :y 211409.4685554395} {:x 125, :y 209749.99357222} {:x 126, :y 209090.8633422415} {:x 127, :y 208520.904541022} {:x 128, :y 208043.7645339835} {:x 129, :y 206449.2176246665} {:x 130, :y 207240.5035781715} {:x 131, :y 208836.368389139} {:x 132, :y 209143.883800469} {:x 133, :y 208639.2059707545} {:x 134, :y 211168.762874581} {:x 135, :y 211996.1928558375} {:x 136, :y 210110.8989715575} {:x 137, :y 209395.283145862} {:x 138, :y 210747.7878951915} {:x 139, :y 212329.9674033845} {:x 140, :y 213707.5673293895} {:x 141, :y 213896.599712353} {:x 142, :y 213335.6060027905} {:x 143, :y 213933.286266332} {:x 144, :y 213891.3928031725} {:x 145, :y 213957.654590577} {:x 146, :y 214666.4510726965} {:x 147, :y 216659.795761093} {:x 148, :y 216400.8012008725} {:x 149, :y 216329.976921091} {:x 150, :y 216785.163497936} {:x 151, :y 217086.663837438} {:x 152, :y 216876.3449096475} {:x 153, :y 216981.7884635895} {:x 154, :y 217809.2418098565} {:x 155, :y 218791.4202689955} {:x 156, :y 218026.2186050035} {:x 157, :y 217203.0135536065} {:x 158, :y 217970.0837707525} {:x 159, :y 218729.5413971015} {:x 160, :y 219051.67634960602} {:x 161, :y 220984.472732518} {:x 162, :y 221123.357887227} {:x 163, :y 220347.864818556} {:x 164, :y 220814.40694808} {:x 165, :y 221110.4021262845} {:x 166, :y 222476.4763641225} {:x 167, :y 223850.774040202} {:x 168, :y 224163.5145187165} {:x 169, :y 224515.364131909} {:x 170, :y 225481.56459806502} {:x 171, :y 224981.879158003} {:x 172, :y 224091.9942664765} {:x 173, :y 223082.8681754835} {:x 174, :y 224254.780273421} {:x 175, :y 224372.1410942155} {:x 176, :y 224665.8438873235} {:x 177, :y 224053.7555122055} {:x 178, :y 224152.69153592} {:x 179, :y 225283.478260042} {:x 180, :y 226985.069332104} {:x 181, :y 228298.25336454602} {:x 182, :y 228438.2802963105} {:x 183, :y 228934.5385169735} {:x 184, :y 230777.361869798} {:x 185, :y 229438.0132675125} {:x 186, :y 229216.7705535765} {:x 187, :y 229945.6987571605} {:x 188, :y 230256.30201338348} {:x 189, :y 227841.00788113102} {:x 190, :y 227103.4130286855} {:x 191, :y 225890.679111463} {:x 192, :y 227435.09809491748} {:x 193, :y 227527.222537985} {:x 194, :y 223230.5912017595} {:x 195, :y 222036.864242504} {:x 196, :y 223403.87006756398} {:x 197, :y 223487.85125729349} {:x 198, :y 222549.8225211735} {:x 199, :y 225577.308139778} {:x 200, :y 223760.9089088325} {:x 201, :y 221411.4437293865} {:x 202, :y 216609.6567534965} {:x 203, :y 218274.1766547875} {:x 204, :y 217248.9762496915} {:x 205, :y 219523.1471252095} {:x 206, :y 220266.2115860015} {:x 207, :y 220897.133827179} {:x 208, :y 223374.2358970395} {:x 209, :y 224135.0770568425} {:x 210, :y 225884.5863914155} {:x 211, :y 226675.013771029} {:x 212, :y 228489.1572952135} {:x 213, :y 228562.3737525745} {:x 214, :y 228895.71252821852} {:x 215, :y 227587.5681113855} {:x 216, :y 229102.27090830798} {:x 217, :y 228905.5615996925} {:x 218, :y 228809.90947721002} {:x 219, :y 227835.2689742765} {:x 220, :y 226811.5306663425} {:x 221, :y 227654.5632552825} {:x 222, :y 224564.0935897455} {:x 223, :y 223866.154880488} {:x 224, :y 224260.3366661045} {:x 225, :y 222426.34246826402} {:x 226, :y 223127.8765296725} {:x 227, :y 223941.9772338655} {:x 228, :y 225983.423500051} {:x 229, :y 227386.0654067855} {:x 230, :y 228284.438056919} {:x 231, :y 228368.872737871} {:x 232, :y 228386.2299537645} {:x 233, :y 227701.830406172} {:x 234, :y 230034.142932886} {:x 235, :y 229944.7773551725} {:x 236, :y 230138.3947372295} {:x 237, :y 231364.317932113} {:x 238, :y 231266.6678809975} {:x 239, :y 232061.9403648245} {:x 240, :y 231778.365993481} {:x 241, :y 231978.0772018175} {:x 242, :y 231219.8146438645} {:x 243, :y 230719.416656495} {:x 244, :y 230880.170688623} {:x 245, :y 231841.55820843249} {:x 246, :y 231097.497692097} {:x 247, :y 232414.724826799} {:x 248, :y 232854.765586851} {:x 249, :y 232879.0609741125} {:x 250, :y 232955.474586467} {:x 251, :y 234064.6536445475} {:x 252, :y 232827.308578456} {:x 253, :y 233624.769992794} {:x 254, :y 233589.5029067705} {:x 255, :y 234036.51655195502} {:x 256, :y 234114.3051719505} {:x 257, :y 234247.21010207452} {:x 258, :y 232759.02112959352} {:x 259, :y 233898.69514461598} {:x 260, :y 234378.1956481785} {:x 261, :y 234894.9417495345} {:x 262, :y 235007.529106131} {:x 263, :y 234582.76254651} {:x 264, :y 231974.2527008155} {:x 265, :y 232100.174217197} {:x 266, :y 232017.5571441405} {:x 267, :y 233719.9002074905} {:x 268, :y 237840.29542918748} {:x 269, :y 239638.7348174965} {:x 270, :y 240170.78592298698} {:x 271, :y 241384.86026760697} {:x 272, :y 241007.97464367998} {:x 273, :y 240574.3055724955} {:x 274, :y 239522.8641318995} {:x 275, :y 237088.4553527525} {:x 276, :y 238343.89791485848} {:x 277, :y 239457.4205016885} {:x 278, :y 239701.322784386} {:x 279, :y 239973.37356564} {:x 280, :y 239552.0639037735} {:x 281, :y 240234.25193783653} {:x 282, :y 240071.0241889725} {:x 283, :y 239706.731357568} {:x 284, :y 240616.0608291395} {:x 285, :y 241440.928611735} {:x 286, :y 241570.04623414698} {:x 287, :y 243021.8405914225} {:x 288, :y 243043.376197786} {:x 289, :y 243652.82417293498} {:x 290, :y 243208.40456008748} {:x 291, :y 242806.891231519} {:x 292, :y 244868.837547279} {:x 293, :y 244305.6034087735} {:x 294, :y 243616.19625087548} {:x 295, :y 244576.36032100697} {:x 296, :y 244813.0298041785} {:x 297, :y 240944.455814348} {:x 298, :y 240436.3371658005} {:x 299, :y 241495.076847057} {:x 300, :y 242845.23145673} {:x 301, :y 244348.02936551452} {:x 302, :y 245199.281616203} {:x 303, :y 243198.3929252455} {:x 304, :y 241330.670928935} {:x 305, :y 240799.222946144} {:x 306, :y 239964.860591877} {:x 307, :y 241665.2047729175} {:x 308, :y 244388.5189247045} {:x 309, :y 241851.9705581555} {:x 310, :y 241256.7307853605} {:x 311, :y 239011.71306609552} {:x 312, :y 238422.943057995} {:x 313, :y 239499.341583237} {:x 314, :y 242178.16839214799} {:x 315, :y 242266.258602121} {:x 316, :y 243624.09843442298} {:x 317, :y 245436.21141431452} {:x 318, :y 246140.3289413135} {:x 319, :y 246554.361419645} {:x 320, :y 246079.3128585505} {:x 321, :y 240832.0218086025} {:x 322, :y 242789.041023247} {:x 323, :y 241887.8588676145} {:x 324, :y 243245.2753066815} {:x 325, :y 242057.62161253148} {:x 326, :y 240267.08185191048} {:x 327, :y 241369.18394087} {:x 328, :y 242139.87621305598} {:x 329, :y 242501.2777328435} {:x 330, :y 241284.632072423} {:x 331, :y 242043.475894903} {:x 332, :y 241671.1778831505} {:x 333, :y 240243.1269645435} {:x 334, :y 242582.9242706335})}], :marks [{:type \"line\", :from {:data \"60893bb2-3a47-49e8-aae9-1d293fb11e70\"}, :properties {:enter {:x {:scale \"x\", :field \"data.x\"}, :y {:scale \"y\", :field \"data.y\"}, :stroke {:value \"#7f3b08\"}, :strokeWidth {:value 3}, :strokeOpacity {:value 1}}}}], :scales [{:name \"x\", :type \"linear\", :range \"width\", :zero false, :domain {:data \"60893bb2-3a47-49e8-aae9-1d293fb11e70\", :field \"data.x\"}} {:name \"y\", :type \"linear\", :range \"height\", :nice true, :zero false, :domain {:data \"60893bb2-3a47-49e8-aae9-1d293fb11e70\", :field \"data.y\"}}], :axes [{:type \"x\", :scale \"x\", :title \"Day\", :titleOffset 40, :grid true} {:type \"y\", :scale \"y\", :title \"Portfolio Value (in $)\", :titleOffset 65, :grid true}]}}"}
;; <=

;; **
;;; #### 30 Day Rolling Volatility
;; **

;; @@
(plot/list-plot (rolling-volatility (map second portfolio-value-by-day) 21) :joined true :plot-size 800 :x-title "Time" :y-title "Portfolio Volatility" :color "red") ;; 21 trading days in a month therefore 21 window-size used
;; @@
;; =>
;;; {"type":"vega","content":{"width":800,"height":494.4376,"padding":{"top":10,"left":80,"bottom":50,"right":10},"data":[{"name":"097efba0-77e3-4f4b-a2ca-ae1cb97d220c","values":[{"x":0,"y":0.3335876812216949},{"x":1,"y":0.3333102021306854},{"x":2,"y":0.32213185021677815},{"x":3,"y":0.3155864812602281},{"x":4,"y":0.3106064558405756},{"x":5,"y":0.31112409119109014},{"x":6,"y":0.31047134951923205},{"x":7,"y":0.29403165593763086},{"x":8,"y":0.2869752792354369},{"x":9,"y":0.2824072435821138},{"x":10,"y":0.2811929131804454},{"x":11,"y":0.28118732949919745},{"x":12,"y":0.28090418362600755},{"x":13,"y":0.3362150237039229},{"x":14,"y":0.3323721271265157},{"x":15,"y":0.31414296836574945},{"x":16,"y":0.3181947721410445},{"x":17,"y":0.3178850999116508},{"x":18,"y":0.3043209405540964},{"x":19,"y":0.28473072039264413},{"x":20,"y":0.3283054612018316},{"x":21,"y":0.2950936363533218},{"x":22,"y":0.29788947150084183},{"x":23,"y":0.297957821264126},{"x":24,"y":0.30093873243128444},{"x":25,"y":0.3206265075045767},{"x":26,"y":0.32606080242732227},{"x":27,"y":0.3260552547391579},{"x":28,"y":0.32660212365297886},{"x":29,"y":0.32550601025420567},{"x":30,"y":0.3275657025215701},{"x":31,"y":0.33209838435760686},{"x":32,"y":0.3429353765358037},{"x":33,"y":0.34608572435670354},{"x":34,"y":0.28751304715801074},{"x":35,"y":0.2876967009899416},{"x":36,"y":0.30079447923846864},{"x":37,"y":0.29925407326216913},{"x":38,"y":0.29950095076154565},{"x":39,"y":0.2992533069819653},{"x":40,"y":0.2987953192863004},{"x":41,"y":0.25810516514576204},{"x":42,"y":0.254866149495886},{"x":43,"y":0.26309901608422026},{"x":44,"y":0.277391888094934},{"x":45,"y":0.272822411631098},{"x":46,"y":0.24859044757931234},{"x":47,"y":0.2380983833453039},{"x":48,"y":0.24754294767043847},{"x":49,"y":0.24502675913722466},{"x":50,"y":0.25290097119239535},{"x":51,"y":0.2516938639404447},{"x":52,"y":0.2781665977490334},{"x":53,"y":0.2900014120850896},{"x":54,"y":0.2805216711740875},{"x":55,"y":0.2865155494816818},{"x":56,"y":0.28799889017756897},{"x":57,"y":0.2730899954762095},{"x":58,"y":0.27229187437305025},{"x":59,"y":0.273125512481751},{"x":60,"y":0.27345045084273883},{"x":61,"y":0.32617100070310634},{"x":62,"y":0.32441681423060437},{"x":63,"y":0.31889485662017003},{"x":64,"y":0.32790267275245133},{"x":65,"y":0.3287770274795307},{"x":66,"y":0.3293037294815628},{"x":67,"y":0.43345184134475834},{"x":68,"y":0.4329941626679669},{"x":69,"y":0.43579122698837347},{"x":70,"y":0.43507419321940943},{"x":71,"y":0.43195161635323764},{"x":72,"y":0.4355207620299283},{"x":73,"y":0.42863902349045335},{"x":74,"y":0.41730989766975735},{"x":75,"y":0.4350083429990142},{"x":76,"y":0.4301931019766358},{"x":77,"y":0.44387636494950766},{"x":78,"y":0.4515250600646472},{"x":79,"y":0.45377543748356464},{"x":80,"y":0.47372634115701906},{"x":81,"y":0.4752375042635738},{"x":82,"y":0.44947749881167154},{"x":83,"y":0.45713404316904377},{"x":84,"y":0.46629697048532914},{"x":85,"y":0.4595164386058819},{"x":86,"y":0.45678550263727774},{"x":87,"y":0.4537929529984124},{"x":88,"y":0.3680484423070468},{"x":89,"y":0.36917205314677276},{"x":90,"y":0.3606608271451677},{"x":91,"y":0.3635503222076227},{"x":92,"y":0.362214394017434},{"x":93,"y":0.3631543512283864},{"x":94,"y":0.36591616483986145},{"x":95,"y":0.36500664997373533},{"x":96,"y":0.3686160009868199},{"x":97,"y":0.3714548037946522},{"x":98,"y":0.34941235031038725},{"x":99,"y":0.3398145658168385},{"x":100,"y":0.36754256419051223},{"x":101,"y":0.3552100537884288},{"x":102,"y":0.3805745989075449},{"x":103,"y":0.4104911373675723},{"x":104,"y":0.4063432676169891},{"x":105,"y":0.3862478515463176},{"x":106,"y":0.37949173930512164},{"x":107,"y":0.37972376254107454},{"x":108,"y":0.38760246770914036},{"x":109,"y":0.4350626817743104},{"x":110,"y":0.43841616661546856},{"x":111,"y":0.43889028463337243},{"x":112,"y":0.5188827572147485},{"x":113,"y":0.5284683642203447},{"x":114,"y":0.5596125784274236},{"x":115,"y":0.5551541026313238},{"x":116,"y":0.5765957858005668},{"x":117,"y":0.5904048437365795},{"x":118,"y":0.6015984690152114},{"x":119,"y":0.601747371657989},{"x":120,"y":0.6047872231343512},{"x":121,"y":0.5895919718531768},{"x":122,"y":0.5787866359010398},{"x":123,"y":0.5597025358691639},{"x":124,"y":0.5276769500370915},{"x":125,"y":0.5468606120543223},{"x":126,"y":0.541649748570951},{"x":127,"y":0.5359425616432827},{"x":128,"y":0.48937272202247506},{"x":129,"y":0.4885497503698353},{"x":130,"y":0.47643790569177286},{"x":131,"y":0.47727398993918635},{"x":132,"y":0.46929913005320495},{"x":133,"y":0.4137924085938341},{"x":134,"y":0.4253792135996733},{"x":135,"y":0.3755337089117787},{"x":136,"y":0.35957426357844563},{"x":137,"y":0.3464130500864442},{"x":138,"y":0.3205696102445128},{"x":139,"y":0.34210325963522803},{"x":140,"y":0.3424169832254501},{"x":141,"y":0.34834815007394343},{"x":142,"y":0.34743473462634145},{"x":143,"y":0.3452642129689835},{"x":144,"y":0.3579220867352666},{"x":145,"y":0.36899441718955955},{"x":146,"y":0.32915443229469604},{"x":147,"y":0.322764880567073},{"x":148,"y":0.323613215662024},{"x":149,"y":0.3362688653616438},{"x":150,"y":0.35879912536358033},{"x":151,"y":0.3787880050506773},{"x":152,"y":0.3875274327506644},{"x":153,"y":0.38467962129740996},{"x":154,"y":0.3781190537148745},{"x":155,"y":0.3735961196483959},{"x":156,"y":0.3558257171634449},{"x":157,"y":0.36161556935173644},{"x":158,"y":0.38262493863779345},{"x":159,"y":0.3923832002868046},{"x":160,"y":0.3603625962998612},{"x":161,"y":0.35988363182437827},{"x":162,"y":0.36522999409133927},{"x":163,"y":0.4049834413831104},{"x":164,"y":0.4094850202158198},{"x":165,"y":0.39825111444807204},{"x":166,"y":0.3840757049606737},{"x":167,"y":0.4628754364554174},{"x":168,"y":0.4706241393821022},{"x":169,"y":0.47920464654212425},{"x":170,"y":0.4977168354507443},{"x":171,"y":0.4870575354606869},{"x":172,"y":0.6411313659732083},{"x":173,"y":0.6398563402114097},{"x":174,"y":0.6557675720941006},{"x":175,"y":0.655020120000007},{"x":176,"y":0.6586033460489731},{"x":177,"y":0.7252674687094052},{"x":178,"y":0.7388533481397546},{"x":179,"y":0.7479206864887737},{"x":180,"y":0.853273553571159},{"x":181,"y":0.8795739463547817},{"x":182,"y":0.8755454493837479},{"x":183,"y":0.8914989030097803},{"x":184,"y":0.8961853113011102},{"x":185,"y":0.9020642609981776},{"x":186,"y":0.9401170830338547},{"x":187,"y":0.9441171152146538},{"x":188,"y":0.9388901158941905},{"x":189,"y":0.940105437078686},{"x":190,"y":0.9476090720961665},{"x":191,"y":0.9367289082888591},{"x":192,"y":0.937082609915175},{"x":193,"y":0.8412536557332089},{"x":194,"y":0.8370590033825993},{"x":195,"y":0.8316367442255859},{"x":196,"y":0.8322065187078339},{"x":197,"y":0.8324081906831532},{"x":198,"y":0.7896259875573184},{"x":199,"y":0.7689540375070525},{"x":200,"y":0.7941659475423382},{"x":201,"y":0.6156867035773178},{"x":202,"y":0.5997239433230481},{"x":203,"y":0.6215602735422184},{"x":204,"y":0.5861651025165165},{"x":205,"y":0.586776160964677},{"x":206,"y":0.6130190403674484},{"x":207,"y":0.5806059095705375},{"x":208,"y":0.5819186192827309},{"x":209,"y":0.5599425021363462},{"x":210,"y":0.5558523132071709},{"x":211,"y":0.53165496120006},{"x":212,"y":0.5781144443392531},{"x":213,"y":0.5777032873446911},{"x":214,"y":0.5614346723375095},{"x":215,"y":0.5549165836963733},{"x":216,"y":0.5544705929294622},{"x":217,"y":0.5576442962261107},{"x":218,"y":0.5480281142079858},{"x":219,"y":0.5342979731809537},{"x":220,"y":0.5388306675344032},{"x":221,"y":0.4345470114080283},{"x":222,"y":0.4230400411486401},{"x":223,"y":0.42707274074788965},{"x":224,"y":0.3815733363964423},{"x":225,"y":0.3899437588359229},{"x":226,"y":0.3879992586436988},{"x":227,"y":0.3519840449838501},{"x":228,"y":0.335136163740732},{"x":229,"y":0.338957712877747},{"x":230,"y":0.36715755572584313},{"x":231,"y":0.3705320862760823},{"x":232,"y":0.35990169939743805},{"x":233,"y":0.29569120946483496},{"x":234,"y":0.2946274459344263},{"x":235,"y":0.29469672933875896},{"x":236,"y":0.315413546550036},{"x":237,"y":0.3303980272699342},{"x":238,"y":0.32567083063291624},{"x":239,"y":0.3253112865472845},{"x":240,"y":0.3252887779282403},{"x":241,"y":0.31802958380882435},{"x":242,"y":0.4061026706237327},{"x":243,"y":0.40603495936473566},{"x":244,"y":0.39615891990093416},{"x":245,"y":0.41904680105728137},{"x":246,"y":0.5521390253841177},{"x":247,"y":0.5697145410367913},{"x":248,"y":0.5692093305997682},{"x":249,"y":0.5737356522994079},{"x":250,"y":0.5735105555613068},{"x":251,"y":0.5579958313441945},{"x":252,"y":0.5708528633076357},{"x":253,"y":0.6222324985579147},{"x":254,"y":0.6297877334739094},{"x":255,"y":0.6349726816110681},{"x":256,"y":0.6348619303530766},{"x":257,"y":0.6114106261811771},{"x":258,"y":0.6100143304109399},{"x":259,"y":0.6108469869829756},{"x":260,"y":0.6117016179502937},{"x":261,"y":0.6141900516791279},{"x":262,"y":0.6137271377511269},{"x":263,"y":0.5457199513808052},{"x":264,"y":0.5457301366192874},{"x":265,"y":0.5501166802812157},{"x":266,"y":0.5390554123544486},{"x":267,"y":0.40159738238041326},{"x":268,"y":0.3783220802729967},{"x":269,"y":0.3800288249070066},{"x":270,"y":0.4069535427124721},{"x":271,"y":0.4093101173482253},{"x":272,"y":0.4129680578070045},{"x":273,"y":0.40258101890852566},{"x":274,"y":0.31109806105250454},{"x":275,"y":0.47890542880517395},{"x":276,"y":0.4723825148296902},{"x":277,"y":0.48099369914606294},{"x":278,"y":0.49420161852583144},{"x":279,"y":0.5057121594590368},{"x":280,"y":0.5070899191146938},{"x":281,"y":0.5442927847609376},{"x":282,"y":0.5723421273339134},{"x":283,"y":0.5691844229905835},{"x":284,"y":0.5686149994147105},{"x":285,"y":0.5908248841645959},{"x":286,"y":0.6274271515075506},{"x":287,"y":0.6692591974316865},{"x":288,"y":0.6679434348659519},{"x":289,"y":0.6950451783896567},{"x":290,"y":0.6957650405892951},{"x":291,"y":0.6741570264507292},{"x":292,"y":0.7238810377922703},{"x":293,"y":0.7218681282641263},{"x":294,"y":0.7275754983833357},{"x":295,"y":0.7460580574208355},{"x":296,"y":0.6517724309490593},{"x":297,"y":0.6478626840831279},{"x":298,"y":0.647022772279768},{"x":299,"y":0.7985977024499116},{"x":300,"y":0.807618011409173},{"x":301,"y":0.8061426864556609},{"x":302,"y":0.7976763568644716},{"x":303,"y":0.7863969577262259},{"x":304,"y":0.8022528297433286},{"x":305,"y":0.804477230663335},{"x":306,"y":0.7924761356906331},{"x":307,"y":0.7513781430798914},{"x":308,"y":0.7241827726168246},{"x":309,"y":0.7253243670604167},{"x":310,"y":0.6936466346661609},{"x":311,"y":0.7051120255984725},{"x":312,"y":0.7292132640970483}]}],"marks":[{"type":"line","from":{"data":"097efba0-77e3-4f4b-a2ca-ae1cb97d220c"},"properties":{"enter":{"x":{"scale":"x","field":"data.x"},"y":{"scale":"y","field":"data.y"},"stroke":{"value":"red"},"strokeWidth":{"value":3},"strokeOpacity":{"value":1}}}}],"scales":[{"name":"x","type":"linear","range":"width","zero":false,"domain":{"data":"097efba0-77e3-4f4b-a2ca-ae1cb97d220c","field":"data.x"}},{"name":"y","type":"linear","range":"height","nice":true,"zero":false,"domain":{"data":"097efba0-77e3-4f4b-a2ca-ae1cb97d220c","field":"data.y"}}],"axes":[{"type":"x","scale":"x","title":"Time","titleOffset":40,"grid":true},{"type":"y","scale":"y","title":"Portfolio Volatility","titleOffset":65,"grid":true}]},"value":"#gorilla_repl.vega.VegaView{:content {:width 800, :height 494.4376, :padding {:top 10, :left 80, :bottom 50, :right 10}, :data [{:name \"097efba0-77e3-4f4b-a2ca-ae1cb97d220c\", :values ({:x 0, :y 0.3335876812216949} {:x 1, :y 0.3333102021306854} {:x 2, :y 0.32213185021677815} {:x 3, :y 0.3155864812602281} {:x 4, :y 0.3106064558405756} {:x 5, :y 0.31112409119109014} {:x 6, :y 0.31047134951923205} {:x 7, :y 0.29403165593763086} {:x 8, :y 0.2869752792354369} {:x 9, :y 0.2824072435821138} {:x 10, :y 0.2811929131804454} {:x 11, :y 0.28118732949919745} {:x 12, :y 0.28090418362600755} {:x 13, :y 0.3362150237039229} {:x 14, :y 0.3323721271265157} {:x 15, :y 0.31414296836574945} {:x 16, :y 0.3181947721410445} {:x 17, :y 0.3178850999116508} {:x 18, :y 0.3043209405540964} {:x 19, :y 0.28473072039264413} {:x 20, :y 0.3283054612018316} {:x 21, :y 0.2950936363533218} {:x 22, :y 0.29788947150084183} {:x 23, :y 0.297957821264126} {:x 24, :y 0.30093873243128444} {:x 25, :y 0.3206265075045767} {:x 26, :y 0.32606080242732227} {:x 27, :y 0.3260552547391579} {:x 28, :y 0.32660212365297886} {:x 29, :y 0.32550601025420567} {:x 30, :y 0.3275657025215701} {:x 31, :y 0.33209838435760686} {:x 32, :y 0.3429353765358037} {:x 33, :y 0.34608572435670354} {:x 34, :y 0.28751304715801074} {:x 35, :y 0.2876967009899416} {:x 36, :y 0.30079447923846864} {:x 37, :y 0.29925407326216913} {:x 38, :y 0.29950095076154565} {:x 39, :y 0.2992533069819653} {:x 40, :y 0.2987953192863004} {:x 41, :y 0.25810516514576204} {:x 42, :y 0.254866149495886} {:x 43, :y 0.26309901608422026} {:x 44, :y 0.277391888094934} {:x 45, :y 0.272822411631098} {:x 46, :y 0.24859044757931234} {:x 47, :y 0.2380983833453039} {:x 48, :y 0.24754294767043847} {:x 49, :y 0.24502675913722466} {:x 50, :y 0.25290097119239535} {:x 51, :y 0.2516938639404447} {:x 52, :y 0.2781665977490334} {:x 53, :y 0.2900014120850896} {:x 54, :y 0.2805216711740875} {:x 55, :y 0.2865155494816818} {:x 56, :y 0.28799889017756897} {:x 57, :y 0.2730899954762095} {:x 58, :y 0.27229187437305025} {:x 59, :y 0.273125512481751} {:x 60, :y 0.27345045084273883} {:x 61, :y 0.32617100070310634} {:x 62, :y 0.32441681423060437} {:x 63, :y 0.31889485662017003} {:x 64, :y 0.32790267275245133} {:x 65, :y 0.3287770274795307} {:x 66, :y 0.3293037294815628} {:x 67, :y 0.43345184134475834} {:x 68, :y 0.4329941626679669} {:x 69, :y 0.43579122698837347} {:x 70, :y 0.43507419321940943} {:x 71, :y 0.43195161635323764} {:x 72, :y 0.4355207620299283} {:x 73, :y 0.42863902349045335} {:x 74, :y 0.41730989766975735} {:x 75, :y 0.4350083429990142} {:x 76, :y 0.4301931019766358} {:x 77, :y 0.44387636494950766} {:x 78, :y 0.4515250600646472} {:x 79, :y 0.45377543748356464} {:x 80, :y 0.47372634115701906} {:x 81, :y 0.4752375042635738} {:x 82, :y 0.44947749881167154} {:x 83, :y 0.45713404316904377} {:x 84, :y 0.46629697048532914} {:x 85, :y 0.4595164386058819} {:x 86, :y 0.45678550263727774} {:x 87, :y 0.4537929529984124} {:x 88, :y 0.3680484423070468} {:x 89, :y 0.36917205314677276} {:x 90, :y 0.3606608271451677} {:x 91, :y 0.3635503222076227} {:x 92, :y 0.362214394017434} {:x 93, :y 0.3631543512283864} {:x 94, :y 0.36591616483986145} {:x 95, :y 0.36500664997373533} {:x 96, :y 0.3686160009868199} {:x 97, :y 0.3714548037946522} {:x 98, :y 0.34941235031038725} {:x 99, :y 0.3398145658168385} {:x 100, :y 0.36754256419051223} {:x 101, :y 0.3552100537884288} {:x 102, :y 0.3805745989075449} {:x 103, :y 0.4104911373675723} {:x 104, :y 0.4063432676169891} {:x 105, :y 0.3862478515463176} {:x 106, :y 0.37949173930512164} {:x 107, :y 0.37972376254107454} {:x 108, :y 0.38760246770914036} {:x 109, :y 0.4350626817743104} {:x 110, :y 0.43841616661546856} {:x 111, :y 0.43889028463337243} {:x 112, :y 0.5188827572147485} {:x 113, :y 0.5284683642203447} {:x 114, :y 0.5596125784274236} {:x 115, :y 0.5551541026313238} {:x 116, :y 0.5765957858005668} {:x 117, :y 0.5904048437365795} {:x 118, :y 0.6015984690152114} {:x 119, :y 0.601747371657989} {:x 120, :y 0.6047872231343512} {:x 121, :y 0.5895919718531768} {:x 122, :y 0.5787866359010398} {:x 123, :y 0.5597025358691639} {:x 124, :y 0.5276769500370915} {:x 125, :y 0.5468606120543223} {:x 126, :y 0.541649748570951} {:x 127, :y 0.5359425616432827} {:x 128, :y 0.48937272202247506} {:x 129, :y 0.4885497503698353} {:x 130, :y 0.47643790569177286} {:x 131, :y 0.47727398993918635} {:x 132, :y 0.46929913005320495} {:x 133, :y 0.4137924085938341} {:x 134, :y 0.4253792135996733} {:x 135, :y 0.3755337089117787} {:x 136, :y 0.35957426357844563} {:x 137, :y 0.3464130500864442} {:x 138, :y 0.3205696102445128} {:x 139, :y 0.34210325963522803} {:x 140, :y 0.3424169832254501} {:x 141, :y 0.34834815007394343} {:x 142, :y 0.34743473462634145} {:x 143, :y 0.3452642129689835} {:x 144, :y 0.3579220867352666} {:x 145, :y 0.36899441718955955} {:x 146, :y 0.32915443229469604} {:x 147, :y 0.322764880567073} {:x 148, :y 0.323613215662024} {:x 149, :y 0.3362688653616438} {:x 150, :y 0.35879912536358033} {:x 151, :y 0.3787880050506773} {:x 152, :y 0.3875274327506644} {:x 153, :y 0.38467962129740996} {:x 154, :y 0.3781190537148745} {:x 155, :y 0.3735961196483959} {:x 156, :y 0.3558257171634449} {:x 157, :y 0.36161556935173644} {:x 158, :y 0.38262493863779345} {:x 159, :y 0.3923832002868046} {:x 160, :y 0.3603625962998612} {:x 161, :y 0.35988363182437827} {:x 162, :y 0.36522999409133927} {:x 163, :y 0.4049834413831104} {:x 164, :y 0.4094850202158198} {:x 165, :y 0.39825111444807204} {:x 166, :y 0.3840757049606737} {:x 167, :y 0.4628754364554174} {:x 168, :y 0.4706241393821022} {:x 169, :y 0.47920464654212425} {:x 170, :y 0.4977168354507443} {:x 171, :y 0.4870575354606869} {:x 172, :y 0.6411313659732083} {:x 173, :y 0.6398563402114097} {:x 174, :y 0.6557675720941006} {:x 175, :y 0.655020120000007} {:x 176, :y 0.6586033460489731} {:x 177, :y 0.7252674687094052} {:x 178, :y 0.7388533481397546} {:x 179, :y 0.7479206864887737} {:x 180, :y 0.853273553571159} {:x 181, :y 0.8795739463547817} {:x 182, :y 0.8755454493837479} {:x 183, :y 0.8914989030097803} {:x 184, :y 0.8961853113011102} {:x 185, :y 0.9020642609981776} {:x 186, :y 0.9401170830338547} {:x 187, :y 0.9441171152146538} {:x 188, :y 0.9388901158941905} {:x 189, :y 0.940105437078686} {:x 190, :y 0.9476090720961665} {:x 191, :y 0.9367289082888591} {:x 192, :y 0.937082609915175} {:x 193, :y 0.8412536557332089} {:x 194, :y 0.8370590033825993} {:x 195, :y 0.8316367442255859} {:x 196, :y 0.8322065187078339} {:x 197, :y 0.8324081906831532} {:x 198, :y 0.7896259875573184} {:x 199, :y 0.7689540375070525} {:x 200, :y 0.7941659475423382} {:x 201, :y 0.6156867035773178} {:x 202, :y 0.5997239433230481} {:x 203, :y 0.6215602735422184} {:x 204, :y 0.5861651025165165} {:x 205, :y 0.586776160964677} {:x 206, :y 0.6130190403674484} {:x 207, :y 0.5806059095705375} {:x 208, :y 0.5819186192827309} {:x 209, :y 0.5599425021363462} {:x 210, :y 0.5558523132071709} {:x 211, :y 0.53165496120006} {:x 212, :y 0.5781144443392531} {:x 213, :y 0.5777032873446911} {:x 214, :y 0.5614346723375095} {:x 215, :y 0.5549165836963733} {:x 216, :y 0.5544705929294622} {:x 217, :y 0.5576442962261107} {:x 218, :y 0.5480281142079858} {:x 219, :y 0.5342979731809537} {:x 220, :y 0.5388306675344032} {:x 221, :y 0.4345470114080283} {:x 222, :y 0.4230400411486401} {:x 223, :y 0.42707274074788965} {:x 224, :y 0.3815733363964423} {:x 225, :y 0.3899437588359229} {:x 226, :y 0.3879992586436988} {:x 227, :y 0.3519840449838501} {:x 228, :y 0.335136163740732} {:x 229, :y 0.338957712877747} {:x 230, :y 0.36715755572584313} {:x 231, :y 0.3705320862760823} {:x 232, :y 0.35990169939743805} {:x 233, :y 0.29569120946483496} {:x 234, :y 0.2946274459344263} {:x 235, :y 0.29469672933875896} {:x 236, :y 0.315413546550036} {:x 237, :y 0.3303980272699342} {:x 238, :y 0.32567083063291624} {:x 239, :y 0.3253112865472845} {:x 240, :y 0.3252887779282403} {:x 241, :y 0.31802958380882435} {:x 242, :y 0.4061026706237327} {:x 243, :y 0.40603495936473566} {:x 244, :y 0.39615891990093416} {:x 245, :y 0.41904680105728137} {:x 246, :y 0.5521390253841177} {:x 247, :y 0.5697145410367913} {:x 248, :y 0.5692093305997682} {:x 249, :y 0.5737356522994079} {:x 250, :y 0.5735105555613068} {:x 251, :y 0.5579958313441945} {:x 252, :y 0.5708528633076357} {:x 253, :y 0.6222324985579147} {:x 254, :y 0.6297877334739094} {:x 255, :y 0.6349726816110681} {:x 256, :y 0.6348619303530766} {:x 257, :y 0.6114106261811771} {:x 258, :y 0.6100143304109399} {:x 259, :y 0.6108469869829756} {:x 260, :y 0.6117016179502937} {:x 261, :y 0.6141900516791279} {:x 262, :y 0.6137271377511269} {:x 263, :y 0.5457199513808052} {:x 264, :y 0.5457301366192874} {:x 265, :y 0.5501166802812157} {:x 266, :y 0.5390554123544486} {:x 267, :y 0.40159738238041326} {:x 268, :y 0.3783220802729967} {:x 269, :y 0.3800288249070066} {:x 270, :y 0.4069535427124721} {:x 271, :y 0.4093101173482253} {:x 272, :y 0.4129680578070045} {:x 273, :y 0.40258101890852566} {:x 274, :y 0.31109806105250454} {:x 275, :y 0.47890542880517395} {:x 276, :y 0.4723825148296902} {:x 277, :y 0.48099369914606294} {:x 278, :y 0.49420161852583144} {:x 279, :y 0.5057121594590368} {:x 280, :y 0.5070899191146938} {:x 281, :y 0.5442927847609376} {:x 282, :y 0.5723421273339134} {:x 283, :y 0.5691844229905835} {:x 284, :y 0.5686149994147105} {:x 285, :y 0.5908248841645959} {:x 286, :y 0.6274271515075506} {:x 287, :y 0.6692591974316865} {:x 288, :y 0.6679434348659519} {:x 289, :y 0.6950451783896567} {:x 290, :y 0.6957650405892951} {:x 291, :y 0.6741570264507292} {:x 292, :y 0.7238810377922703} {:x 293, :y 0.7218681282641263} {:x 294, :y 0.7275754983833357} {:x 295, :y 0.7460580574208355} {:x 296, :y 0.6517724309490593} {:x 297, :y 0.6478626840831279} {:x 298, :y 0.647022772279768} {:x 299, :y 0.7985977024499116} {:x 300, :y 0.807618011409173} {:x 301, :y 0.8061426864556609} {:x 302, :y 0.7976763568644716} {:x 303, :y 0.7863969577262259} {:x 304, :y 0.8022528297433286} {:x 305, :y 0.804477230663335} {:x 306, :y 0.7924761356906331} {:x 307, :y 0.7513781430798914} {:x 308, :y 0.7241827726168246} {:x 309, :y 0.7253243670604167} {:x 310, :y 0.6936466346661609} {:x 311, :y 0.7051120255984725} {:x 312, :y 0.7292132640970483})}], :marks [{:type \"line\", :from {:data \"097efba0-77e3-4f4b-a2ca-ae1cb97d220c\"}, :properties {:enter {:x {:scale \"x\", :field \"data.x\"}, :y {:scale \"y\", :field \"data.y\"}, :stroke {:value \"red\"}, :strokeWidth {:value 3}, :strokeOpacity {:value 1}}}}], :scales [{:name \"x\", :type \"linear\", :range \"width\", :zero false, :domain {:data \"097efba0-77e3-4f4b-a2ca-ae1cb97d220c\", :field \"data.x\"}} {:name \"y\", :type \"linear\", :range \"height\", :nice true, :zero false, :domain {:data \"097efba0-77e3-4f4b-a2ca-ae1cb97d220c\", :field \"data.y\"}}], :axes [{:type \"x\", :scale \"x\", :title \"Time\", :titleOffset 40, :grid true} {:type \"y\", :scale \"y\", :title \"Portfolio Volatility\", :titleOffset 65, :grid true}]}}"}
;; <=
