(ns cim_portfolio.portfoliofunctions
  (:require [cim_portfolio.util :as util]
            [cim_portfolio.yfinanceclient :as client]
            [clojure.math :as math]
            [clojure.pprint :refer [pprint]]
            [clojure.string :as string]))

;;; ### Portfolio Analysis Helper Functions

;; Computes arithmetic, log, and cumulative log return for a given list of prices
(defn calculate-returns [prices]
  (let [price-changes (map #(if (zero? (first %)) ;; Edge case if price is 0 at some point
                              1 
                              (double (/ (second %) (first %)))) 
                           (partition 2 1 prices))
        arithmetic-returns (mapv #(- % 1.0) price-changes)
        log-returns (mapv #(Math/log %) price-changes)
        cumulative-log-return (reduce + log-returns)
        cumulative-arithmetic-return (- (Math/exp cumulative-log-return) 1)]
    {
     :cumulative-log-return cumulative-log-return
     :cumulative-arithmetic-return cumulative-arithmetic-return
     :arithmetic-returns arithmetic-returns
     :log-returns log-returns
     }))

;; Variation of the above function - additionally associates the returns with their corresponding date
(defn calculate-returns-with-corresponding-date [prices dates]
  (let [price-changes (map #(if (zero? (first %)) ;; Edge case which can happen when at some point, portfolio is empty
                               1
                               (double (/ (second %) (first %)))) ;; Next Day (or next date in data) price divided by Current Day Price
                           (partition 2 1 prices));; This transforms a 1D array to a 2D array with a sliding window of size=2 and increment=1
        arithmetic-returns (mapv #(- % 1.0) price-changes) ;; Calculate arithmetic returns from day x to day x+1, day x+1 to day x+2, ...
        log-returns (mapv #(Math/log %) price-changes)
        cumulative-log-return (reduce + log-returns)
        cumulative-arithmetic-return (- (Math/exp cumulative-log-return) 1)]
    {
     :cumulative-log-return cumulative-log-return
     :cumulative-arithmetic-return cumulative-arithmetic-return
     :arithmetic-returns (util/sort-map-by-date (zipmap (rest dates) arithmetic-returns))
     :log-returns (util/sort-map-by-date (zipmap (rest dates) log-returns))
     }))

;; DEPRECATED AS THE BELOW IS WRONG, weights should never be applied to log returns, it should be applied to arithmetic returns.
;; Additionally, weights should be calculated using the current market price of each stock, not the initial cash investment into each stock.

;; Calculates portfolio return - accepts map {:stock cash-invested} and stock-performance generated by calculate-returns (THIS EXCLUDES CASH IN THE CALCULATION)
(defn calculate-portfolio-return [cash-invested returns]
  (let [total-investment (apply + (vals cash-invested))] ;; Total cash investment into portfolio so far
    (->> cash-invested
         (map (fn [[security invested]]
                (let [weight (/ invested total-investment) ;; Weight of each stock in the portfolio
                      return (:cumulative-return (get returns security))] ;; Get cumulative log returns for each security
                  (* weight return)))) ;; Multiply the cumulative log return for each security by its weight
         (apply +))))

;; This function calculates the cumulative portfolio return for a non-static portfolio (changes in the underlying stocks or quantity are considered)
;; This is done by:
;; 1. Taking the portfolio returns from each initial trade date to the next trade date (just before the portfolio composition changes)
;; 2. We transform these returns to log returns
;; 3. Sum all of the log returns together
;; 4. Transform them back to arithmetic returns
(defn calculate-portfolio-cumulative-return [static-returns] ;; a collection
  (let [added-log-returns (reduce + (map #(Math/log (+ % 1)) static-returns))
        final-arithmetic-cumulative-return (- (Math/exp added-log-returns) 1)]
    final-arithmetic-cumulative-return))

;; DEPRECATED (will replace all use of this function with set-of-portfolio-log-returns-and-weights soon)
;; This function calculates the cumulative portfolio return for a static portfolio (no change in the underlying stocks or quantity)
(defn calculate-portfolio-return-and-weights-for-given-date [portfolio start-date end-date] 
  ;; portfolio: The previous portfolio composition before the latest buy/sell order {"NVDA" 10000, "MSFT" 5000, "B" -12500, ...}
  ;; start-date: The trade date for the previous buy/sell order "YYYY-MM-DD"
  ;; end-date: The trade date for the new buy/sell order "YYYY-MM-DD"
  (let [;; Get prices of ticker from start-date (executed date) to end-date
        prices-until-end-date (into {}
                                    (map (fn [[ticker amount]]
                                           [ticker (client/get-ticker-price-with-end ticker start-date end-date)])
                                         portfolio))

        ;; Get the initial total market value of each stock holding in the portfolio
        initial-market-values (into {}
                                    (map (fn [[ticker amount]]
                                           [ticker (* amount (second (first (get prices-until-end-date ticker))))]) ;; Make sure to get opening price, not closing price
                                         portfolio))

        ;; Initial portfolio value (should be the same as the initial cash invested into the portfolio)
        initial-portfolio-value (reduce + (vals initial-market-values))

        ;; Get the current total market value of each stock holding in the portfolio
        current-market-values (into {}
                                    (map (fn [[ticker amount]]
                                           [ticker (* amount (last (last (get prices-until-end-date ticker))))]) ;; Make sure to get closing price, not opening price
                                         portfolio))

        ;; Current portfolio value
        current-portfolio-value (reduce + (vals current-market-values))
        
        ;; Get the current stock weights
        stock-weights (if 
                       (zero? current-portfolio-value) ;; Take care of edge case when there are no stocks in portfolio 
                        (into {} 
                              (map (fn [[ticker value]] 
                                     [ticker (double 0)]) 
                                   current-market-values)) 
                        (into {} 
                              (map (fn [[ticker value]] 
                                     [ticker (/ value current-portfolio-value)]) 
                                   current-market-values))) 
        
        
        ;; Get the portfolio cumulative return
        portfolio-cumulative-return (if (zero? initial-portfolio-value) ;; edge case where portfolio value is 0
                                      0 ;; undefined
                                      (- (/ current-portfolio-value initial-portfolio-value) 1))]
        
        {:portfolio-cumulative-return portfolio-cumulative-return 
         :stock-weights stock-weights
         :initial-portfolio-value initial-portfolio-value
         :current-portfolio-value current-portfolio-value
         :current-stock-holdings current-market-values
         :all-ticker-prices prices-until-end-date}
        ))

;; DEPRECATED, This function calculates the cumulative portfolio return using log returns for a fixed portfolio, returning information about the portfolio
;; Multiple variables are returned to prevent the need to fetch to yfinance multiple times, which causes increased computation time and risks rate limiting
(defn portfolio-log-and-cumulative-returns [portfolio start-date end-date]
  (let [;; Get prices of ticker from start-date (executed date) to end-date
        prices-until-end-date (into {}
                                    (map (fn [[ticker amount]]
                                           [ticker (client/get-ticker-price-with-end ticker start-date end-date)])
                                         portfolio))

        ;; Make dates the keys, and opening and closing prices the values
        prices-until-end-date-enhanced (into {}
                                             (map (fn [[ticker prices]]
                                                    [ticker (into {}
                                                                  (map (fn [[date opening-price closing-price]]
                                                                         [date [opening-price closing-price]])
                                                                       prices))])
                                                  prices-until-end-date))

        ;; Get all trade dates between start-date and end-date
        all-trade-dates (map #(first %) ;; Get all trade dates from the data
                             (get prices-until-end-date ;; Get Prices for any one of the tickers from the portfolio
                                  (first (keys portfolio)))) ;; Get any one of the tickers from the portfolio 

        ;; Get the values of each holding on each trade date
        ;; Returns the following format: {"2025-01-10" {"NVDA" ($100 * 25 units) "MSFT" ($100 * 25 units) ...}, 
        ;;                                "2025-01-13" {"NVDA" ($101 * 25 units) "MSFT" ($99 * 25 units) ...}, ...}
        holding-values-by-date (into {}
                                     (map (fn [d]
                                            [d (into {} ;; Date is set as key
                                                     (map (fn [[ticker prices]]
                                                            [ticker ;; Ticker is inner map's key
                                                             (if (= d start-date) 
                                                               (* (first (get prices d)) (get portfolio ticker)) ;; Multiply opening price of stock at trade date by the amount in portfolio to get holding value
                                                               (* (last (get prices d)) (get portfolio ticker))) ;; Multiply closing price of stock at trade date by the amount in portfolio to get holding value
                                                             ])
                                                          prices-until-end-date-enhanced) ;; For each ticker, get date-prices key-value pair
                                                     )])
                                          all-trade-dates)) ;; For each trade date 

        ;; Get total portfolio value by date
        portfolio-value-by-date (util/sort-map-by-date 
                                 (into {}
                                       (map (fn [[d holdings]]
                                              [d (reduce + (vals holdings))])
                                            holding-values-by-date)))

        ;; Get portfolio weights by date
        ;; Returns the following format: {"2025-01-10" {"NVDA" 20% "MSFT" 100% "TSLA" -20% ...}, 
        ;;                                "2025-01-13" {"NVDA" 10% "MSFT" 100% "TSLA" -10% ...}, ...}
        portfolio-weights-by-date (into {}
                                        (map (fn [[d portfolio-value]]
                                               [d (into {}
                                                        (map (fn [ticker]
                                                               [ticker (/ (get (get holding-values-by-date d) ticker) portfolio-value)]) ;; Divides the stock holdings on date "d", by the total portfolio value on date "d"
                                                             (keys portfolio)))])
                                             portfolio-value-by-date))
        
        portfolio-returns-with-date (calculate-returns-with-corresponding-date (vals portfolio-value-by-date) (keys portfolio-value-by-date)) ;; When using this function, arguments have to be ordered by time
        ]
    {:stock-weights portfolio-weights-by-date
     :portfolio-returns portfolio-returns-with-date ;; Contains arithmetic and log returns and cumulative returns
     :all-ticker-prices prices-until-end-date-enhanced}))


;; This function calculates the log returns for a set of portfolios over time (portfolio-composition-by-date), returning information about each portfolio while they existed
;; Multiple variables are returned to prevent the need to fetch to yfinance multiple times, which causes increased computation time and risks rate limiting
;; This function excludes the consideration of CASH
(defn set-of-portfolio-log-returns-and-weights-without-cash [portfolio-composition-by-date complete-stock-prices]
  (let [;; Java Date Parser
        date-formatter (java.time.format.DateTimeFormatter/ofPattern "yyyy-MM-dd")
        date-parser (fn [d] (java.time.LocalDate/parse d date-formatter))

        ;; Get latest order execution date
        latest-execution-date (.toString
                               (reduce #(if (> (.compareTo %1 %2) 0) %1 %2) ;; .compareTo returns a positive integer if %1 is greater than %0, zero if they are equal, otherwise negative integer
                                       (map date-parser
                                            (keys portfolio-composition-by-date))))

        ;; Get prices of all past and current tickers from start-date (executed date) to end-date 
        ;; prices-until-end-date (into {} ;; this makes everything unsorted
        ;;                             (map (fn [[ticker amount]]
        ;;                                    [ticker (client/get-ticker-price-with-end ticker start-date end-date)])
        ;;                                  (get portfolio-composition-by-date latest-execution-date))) ;; Newest Portfolio should contain all past and current tickers

        ;; Get all prices from previous fetch in analyze-portfolio function
        sorted-prices-until-end-date-enhanced complete-stock-prices

        ;; ;; Sort all the price data
        ;; sorted-prices-until-end-date-enhanced (loop 
        ;;                                        [tickers (keys prices-until-end-date-enhanced) 
        ;;                                         sorted-prices {}] 
        ;;                                         (if (empty? tickers) 
        ;;                                           sorted-prices 
        ;;                                           (recur 
        ;;                                            (rest tickers) 
        ;;                                            (assoc sorted-prices (first tickers) 
        ;;                                                   (util/sort-map-by-date (get prices-until-end-date-enhanced (first tickers)))))))


        ;; Get all trade dates between start of portfolio and today
        ;; Returns a collection of date Strings (i.e. "yyyy-MM-dd")
        all-trade-dates (keys ;; Return the dates 
                         (reduce ;; Find the ticker with the most number of data, and return the corresponding data
                          (fn [best curr] 
                            (if (> (count curr) (count best)) 
                              curr best))
                          {} 
                          (vals sorted-prices-until-end-date-enhanced))) ;; Get all the ticker prices from the newest portfolio

        ;; Get all portfolio-composition-by-date execution dates (already converted into java.time.LocalDate)
        all-trade-execution-dates (map date-parser (keys portfolio-composition-by-date)) ;; Take All Order Execution Dates


        ;; Function to get the latest order execution date before an input date (input-date is a String, not java.time.LocalDate)
        ;; If there are no order execution dates earlier than the input date, then return earliest order execution date
        get-nearest-execution-date (fn [input-date]
                                     (.toString ;; Result will be a java.time.LocalDate, so convert to String
                                      (if
                                       (nil? (reduce (fn [best d] ;; Get the latest order execution date relative to input-date
                                                       (if (and (or (.isBefore d (date-parser input-date)) (.isEqual d (date-parser input-date)))
                                                                (or (nil? best) (.isAfter d best)))
                                                         d
                                                         best))
                                                     nil all-trade-execution-dates)) ;; if reduce returns "nil", then no order exists before each start date 
                                        ;; If there are no execution dates earlier than input-date, then return earliest execution date
                                        (reduce #(if (neg? (.compareTo %1 %2)) %1 %2) ;; Get minimum date in portfolio-composition-by-date
                                                (map date-parser (keys portfolio-composition-by-date)))
                                        ;; Otherwise return the latest order execution date relative to input-date (same expression as condition)
                                        (reduce (fn [best d]
                                                  (if (and (or (.isBefore d (date-parser input-date)) (.isEqual d (date-parser input-date)))
                                                           (or (nil? best) (.isAfter d best)))
                                                    d
                                                    best))
                                                nil all-trade-execution-dates))))

        ;; Get the values of each holding on each trade date based on the existing portfolio on that date
        ;; Returns the following format: {"2025-01-10" {"NVDA" ($100 * 25 units) "MSFT" ($100 * 25 units) ...}, 
        ;;                                "2025-01-13" {"NVDA" ($101 * 25 units) "MSFT" ($99 * 25 units) ...}, ...}
        holding-values-by-date (util/sort-map-by-date
                                (into {}
                                      (map (fn [d]
                                             [d (into {} ;; Date is set as key
                                                      (map (fn [[ticker prices]]
                                                             [ticker ;; Ticker is inner map's key
                                                              (if (= d (first (keys (get sorted-prices-until-end-date-enhanced ticker))))
                                                                ;; Multiply price of stock at trade date by the amount in existing portfolio to get holding value
                                                                ;; Use opening price only if trade date is the first execution date of that stock, otherwise always use closing price (This is correct even if the same stock is bought/sold in a future date, because we only care about the stock holdings at the end of day, this is not a measure of PnL (but should it be? Seems too complicated tho...)!!!)
                                                                (* (first (get prices d [0 0])) (get (get portfolio-composition-by-date (get-nearest-execution-date d)) ticker 0)) ;; Notice that if ticker is not in existing portfolio, amount is 0
                                                                (* (last (get prices d [0 0])) (get (get portfolio-composition-by-date (get-nearest-execution-date d)) ticker 0))) ;; Notice that if ticker is not in existing portfolio, amount is 0
                                                              ])
                                                           sorted-prices-until-end-date-enhanced) ;; For each ticker, get date-prices key-value pair
                                                      )])
                                           all-trade-dates)) ; For each trade date 
                                )
        ;; Get total portfolio value by date (using the existing portfolio on that date), sorted by date
        portfolio-value-by-date (util/sort-map-by-date
                                 (into {}
                                       (map (fn [[d holdings]]
                                              [d (reduce + (vals holdings))])
                                            holding-values-by-date)))

        ;; Get portfolio weights by date
        ;; Returns the following format: {"2025-01-10" {"NVDA" 20% "MSFT" 100% "TSLA" -20% ...}, 
        ;;                                "2025-01-13" {"NVDA" 10% "MSFT" 100% "TSLA" -10% ...}, ...}
        portfolio-weights-by-date (util/sort-map-by-date
                                   (into {} ;; This is unsorted, becareful 
                                         (map (fn [[d portfolio-value]]
                                                [d (if (zero? portfolio-value) ;; Take care of edge case when portfolio value is 0 (no stocks held in portfolio)  
                                                     (into {}
                                                           (map (fn [ticker]
                                                                  [ticker (double 0)])
                                                                ;; (keys (get portfolio-composition-by-date latest-execution-date))
                                                                (keys sorted-prices-until-end-date-enhanced)
                                                                ))
                                                     (into {}
                                                           (map (fn [ticker]
                                                                  [ticker (/ (get (get holding-values-by-date d) ticker) portfolio-value)]) ;; Divides the stock holdings on date "d", by the total portfolio value on date "d"
                                                                ;; (keys (get portfolio-composition-by-date latest-execution-date)) ;; Newest Portfolio should contain all past and current tickers
                                                                (keys sorted-prices-until-end-date-enhanced)
                                                                )))]) 
                                              portfolio-value-by-date)))


        ;; This variable holds all of the time-series log returns of the portfolio
        ;; On the trade date when a new order execution happens, we need to replace return with 0 because the portfolio changes. There is no return on these dates since there is a change in the portfolio composition.
        portfolio-log-returns-by-date (reduce
                                       (fn [m d]
                                         (assoc m d 0)) ;; This essentially makes it so that execution dates are given 0 log return.
                                       (:log-returns (calculate-returns-with-corresponding-date (vals portfolio-value-by-date) (keys portfolio-value-by-date))) ;; When using this function, arguments have to be ordered by time
                                       (keys portfolio-composition-by-date))]

    {:stock-weights portfolio-weights-by-date
     :current-stock-holdings holding-values-by-date
     :portfolio-log-returns portfolio-log-returns-by-date
     :portfolio-value portfolio-value-by-date

     ;; For testing purposes
     ;;  :portfolio-holdings-by-date holding-values-by-date
     }))

;; Same function as above but include cash in the portfolio!!!
;; This function includes cash in the portfolio
(defn set-of-portfolio-log-returns-and-weights [portfolio-composition-by-date portfolio-value-by-day start-date end-date]
  (let [;; Java Date Parser
        date-formatter (java.time.format.DateTimeFormatter/ofPattern "yyyy-MM-dd")
        date-parser (fn [d] (java.time.LocalDate/parse d date-formatter))

        ;; This variable holds all of the time-series log returns of the portfolio from start-date to end-date, in the form of a time-sorted map with trade dates as keys, and log returns as values.
        ;; On the trade date when a new order execution happens, we don't have to replace return with 0 because cash is included in portfolio.
        portfolio-log-returns-by-date 
        (util/sort-map-by-date
         (into {} ;; This will make it unsorted

               ;; Filter for only data after start-date and before end-date  
               (filter
                (fn [[date log-returns]]
                  (and (or (.isAfter (date-parser date) (date-parser start-date)) (.isEqual (date-parser date) (date-parser start-date)))
                       (or (.isBefore (date-parser date) (date-parser end-date)) (.isEqual (date-parser date) (date-parser end-date)))))

                (:log-returns (calculate-returns-with-corresponding-date (map #(second %) portfolio-value-by-day) (map #(first %) portfolio-value-by-day))) ;; When using this function, arguments have to be ordered by time
                )))
        
        
        
        ]

    {:portfolio-log-returns portfolio-log-returns-by-date
     }))


;; Calculates cumulative return UP TILL a given date
(defn get-cumulative-return-till-given-date [cumulative-returns date]
  (util/sum-up-to-key date cumulative-returns) ;; Sum all log returns until a date
)

;; Only calculates portfolio return up till a given date
;; DEPRECATED AS THE BELOW IS WRONG, weights should never be applied to log returns, it should be applied to arithmetic returns.
;; Additionally, weights should be calculated using the current market price of each stock, not the initial cash investment into each stock.

(defn calculate-portfolio-return-for-given-date [cash-invested returns date]
  (let [total-investment (apply + (vals cash-invested))]
    (->> cash-invested
         (map (fn [[security invested]]
                (let [weight (/ invested total-investment)
                      return (get-cumulative-return-till-given-date (:log-returns (get returns security)) date) ;; They sum all log returns for each security until a given date
                     ]
                  (* weight return))))
         (apply +)))) ;; Add up all the weighted returns to get the weighted average return

; Calculates the annualized return of the portfolio (accepts the starting value, ending value of portfolio, the start and end date)
(defn calculate-annualized-return [starting-value ending-value start-date end-date]
  (let [return (/ (- ending-value starting-value) starting-value)
        number-of-days (util/number-of-days-between start-date end-date)
       ]
    (- (math/pow (+ 1 return) (/ 365 number-of-days)) 1)
  )
)

; Calculates the volatility of a given list of prices (expected input: portfolio value list)
(defn volatility [prices]
  (let [daily-returns (:arithmetic-returns (calculate-returns prices))
        volatility (* 100 (util/std-dev daily-returns))
       ]
    volatility
  )
)

; Calculates the annualized volatility for a given sliding window-size (using the historical standard deviation method)
(defn rolling-annualized-volatility [prices window-size]
  (let [returns (:arithmetic-returns (calculate-returns prices))
        scaling-factor (Math/sqrt 252)
       ]
    (->> returns
         (partition window-size 1)
         (map util/std-dev)
      	 (map #(* 100 % scaling-factor))
    )
  )
)

;; Calculates the "Annualized" Rolling EWMA volatility (standard deviation) for a given sliding window-size
;; Prices here are the Portfolio values by date (I assume is already sorted), and follow the following structure:
;; (10000, 10001.21, 10011.8, ...)
;; In the future, user may input the alpha parameter in the dashboard. Might also have to make sure that when portfolio is changed, the return is 0.

(defn ewma-rolling-volatility [prices window-size alpha]
  (let [returns (:arithmetic-returns (calculate-returns prices))
        returns-squared (map #(* % %) returns)
    
        ;; Calculate the weights that will be applied to each squared return in a window
        ;; The size of vector "weights" will be the same as the size of the window 
        applied-weights (loop
                         [i (- window-size 1)
                          weights [(- 1 alpha)]]

                          (if (= i 0)

                            weights

                            (recur
                             (- i 1) ;; Decrement i
                             (conj weights ;; Add to "weights" vector
                                   (* (peek weights) (- 1 alpha)))) ;; Multiply previous weight by (1 - alpha)
                            ))

        ;; Reverses the applied weights
        reversed-applied-weights (rseq applied-weights)

        ;; Apply Sliding Window
        rolling-returns-squared (partition window-size 1 returns-squared)

        ;; Rolling EWMA Variance
        ;; Structure: [0.12, 3, 2.11, ...]

        ;; Calculate the rolling ewma variance with the below steps:
        ;; 1. Multiply each element in each window with the applied weights in reverse order
        ;; 2. Sum all the calculated figures in each window

        rolling-ewma-variance

        (loop
         [sliding-window rolling-returns-squared
          ewma-rolling-portfolio-variance []]

          (if (empty? sliding-window)

            ewma-rolling-portfolio-variance

            (recur
             (rest sliding-window) ;; Remove first window
             (conj ewma-rolling-portfolio-variance
                   (reduce + ;; Sum all products in each window
                                 (map * (first sliding-window) reversed-applied-weights)) ;; Multiply each element in first window, with the corresponding weight
                   )
             ))) 
        
        ;; Rolling EWMA Standard Deviation (just square root the previous variable)
        rolling-ewma-sd (map #(Math/sqrt %) rolling-ewma-variance)

        ;; Annualized EWMA Standard Deviation (just multiply by sqrt 252)
        annualized-rolling-ewma-sd (map #(* (Math/sqrt 252) %) rolling-ewma-sd)
        ]
        
        (vec annualized-rolling-ewma-sd)
        
        ))

;; Calculates the annualized rolling sharpe ratio, intended to be used with a measure of annualized rolling volatility with the same size for the sliding window

(defn rolling-sharpe-ratio [prices volatility window-size]
  (let [returns (:arithmetic-returns (calculate-returns prices))
        rolling-returns (partition window-size 1 returns)
        rolling-average-returns (map #(/ (reduce + %) window-size) rolling-returns)
        annualized-rolling-average-returns (map #(* 252 %) rolling-average-returns)
        rolling-sharpe-ratio (map / annualized-rolling-average-returns volatility)
        ] 
    rolling-sharpe-ratio
    ))

;;; ### Portfolio Processing Section

(defn analyze-portfolio [data]
  (loop [cash 0.0 ;; This is the cash spent by buying or obtained by selling so far
         portfolio {}
         portfolio-composition-by-date (array-map) ;; Even if array-maps sort the data by key, they have a limit of sorting up to 8 items, so please use util/sort-map-by-date
         portfolio-value {}
         current-value 0.0
        ;;  stock-performance {} ;; In the future, may use the commented stock-performance code here and in the below to get the log-returns from trade date.
         cash-invested {}
         cash-invested-by-date (array-map)
         change-in-cash-by-date (array-map) ;; This gets the change in the starting cash by date
         ;; complete-stock-prices looks like the following: {"NVDA" [["2025-01-31" $250 $251], ["2025-02-01" $251.25 $249.27], ...], 
         ;;                                                  "MSFT" [["2025-01-31" $172 $180], ["2025-02-01" $177 $175], ...], 
         ;;                                                  ...}
         ;; and it should have the complete stock prices from the first date the stock appears in the portfolio, 
         ;; and will have prices up till today even if it is not in the portfolio anymore
         complete-stock-prices {}
         data (rest data)]
    (if (empty? data)
      (let [;; Turns price data into cleaner form, where keys are the stock tickers, and values are maps where keys are dates and vals are open and close prices, e.g.
            ;;  {"NVDA" {"2025-01-31" [$250 $251], "2025-02-01" [$251.25 $249.27], ...}, 
            ;;   "MSFT" {"2025-01-31" [$172 $180], "2025-02-01" [$177 $175], ...}, ...}
            complete-stock-prices-enhanced
            (into {}
                  (map (fn [[ticker prices]]
                         [ticker (util/sort-map-by-date ;; Sort by date
                                  (into {} ;; this makes everything (the dates) unsorted 
                                        (map (fn [[date opening-price closing-price]]
                                               [date [opening-price closing-price]])
                                             prices)))])
                       complete-stock-prices))]
        [cash portfolio (util/sort-map-by-date portfolio-composition-by-date) (util/sort-map-by-date portfolio-value) current-value cash-invested (util/sort-map-by-date cash-invested-by-date) (util/sort-map-by-date change-in-cash-by-date) complete-stock-prices-enhanced] ;; When no more rows, return final values
        ) 
      (let [[date action amount ticker set-price] (first data)
           
            ;; Java Datetime related functions
            date-formatter (java.time.format.DateTimeFormatter/ofPattern "yyyy-MM-dd")
            date-parser (fn [d] (java.time.LocalDate/parse d date-formatter))
           
            ticker-prices (filter ;; Filter ticker prices such that only data on the trade date and after is taken  
                           (fn [[d open-price close-price]]
                             (or (.isEqual (date-parser d) (date-parser date))
                                 (.isAfter (date-parser d) (date-parser date))))
           
                           ;; Obtain stock price data (Please check if vector is ordered by date) 
                           (if (= (get complete-stock-prices ticker "") "") ;; Check if we have fetched this ticker previously 
                             (client/get-ticker-price-all ticker (util/parse-date date)) ;; Get prices for only one of the tickers from the trade date until today 
                             (get complete-stock-prices ticker 0)) ;; If already previously fetched, then no need to re-fetch
                           )
            executed-date (first (first ticker-prices))				; gets the date the buy/sell order is executed
            set-price (if (nil? set-price) set-price (str (client/convert-currency ticker set-price))) ;; Converts the inputted price into USD (by default) if not in USD, this returns a string for consistency
            ]
        (cond
          (= (clojure.string/lower-case action) "buy")
          (if (pos? (Double. amount))
            (let [price (if (nil? set-price) (second (first ticker-prices)) (Double. set-price))         ; Gets open price of trading day OR the set-price if available
                  currPrice (nth (last ticker-prices) 2)				; Gets adj close price of latest day
                  prices (mapv #(nth % 2) ticker-prices)       			; Extracts the closing prices from ticker-prices (trade date to today)
                  amounts (repeatedly (count prices) #(Double. amount))	; Repeats amount for num of trading days (trade date to today)
                  ;; trading-dates (mapv #(first %) ticker-prices) ;; List of trading dates
                  ]
              (recur (- cash (* (Double. amount) price)) ;; Cash spent to buy stocks = - (Amount of stocks * Market price of stock when traded)
                     (assoc portfolio ticker (+ (get portfolio ticker 0) (Double. amount))) ;; Updates the current quantity of the stock in the portfolio
                     (assoc portfolio-composition-by-date executed-date (assoc portfolio ticker (+ (get portfolio ticker 0) (Double. amount)))) ;; Save a snapshot of the portfolio composition every order
                     (merge-with + portfolio-value ;; For each trading date, add the new PnL to the existing PnL at that date
                                 (zipmap ;; {T PnL, T+1 PnL, ...}
                                  (map first ticker-prices) ;; Dates for the PnL UNTIL TODAY
                                  (map #(- % (* (Double. amount) price)) (map * prices amounts)))) ;; PnL for each trading day relative to trade date = Market value of each holding for trading days after the trade date - Market value of the holdings on the trade date
                     ; Updates portfolio-value with the calculated values
                     (+ current-value (* (Double. amount) currPrice)) ;; Current (Latest) market value of stocks

                     ;;  (assoc stock-performance ticker (calculate-returns-with-corresponding-date prices trading-dates)) ;; Returns the day to day arithmetic and log returns; Also the cumulative log returns.; Which trading dates depend on data received from client/get-ticker-price-all
                     ;; The above may have problem, especially with the cumulative log return, since it only takes into account the next 30 days only after a trade, will change to up until today 
                     (assoc cash-invested ticker (+ (get cash-invested ticker 0) (* (Double. amount) price))) ;; Updates the amount of cash spent on the trade date so far for each ticker
                     (assoc cash-invested-by-date executed-date (assoc cash-invested ticker (+ (get cash-invested ticker 0) (* (Double. amount) price)))) ;; Same like above but with the trade date
                     ;; Be careful of signage, buy orders should "deplete" cash
                     (assoc change-in-cash-by-date executed-date
                            (if (empty? change-in-cash-by-date)
                              ;; If this is the first trade, just put in the initial investment
                              (- 0 (* (Double. amount) price))

                              ;; Add new trade notional to most recent cash change
                              (- (get change-in-cash-by-date
                                      ;; Get most recent trade date
                                      (.toString
                                       (reduce #(if (> (.compareTo %1 %2) 0) %1 %2) ;; .compareTo returns a positive integer if %1 is greater than %0, zero if they are equal, otherwise negative integer 
                                               (map date-parser
                                                    (keys change-in-cash-by-date)))) 0) (* (Double. amount) price))))
                     (if (= (get complete-stock-prices ticker "") "") ;; Check if we have to store new stock prices into map
                       (assoc complete-stock-prices ticker ticker-prices)
                       complete-stock-prices) ;; Keep previously fetched stock price data
                     (rest data)))
            (recur cash portfolio portfolio-composition-by-date portfolio-value current-value cash-invested cash-invested-by-date change-in-cash-by-date complete-stock-prices (rest data))) ;; If negative amount, ignore
          
          (= (clojure.string/lower-case action) "sell")
          (let [price (if (nil? set-price) (second (first ticker-prices)) (Double. set-price))
                currPrice (nth (last ticker-prices) 2)
                prices (map second ticker-prices)
                amounts (repeatedly (count prices) #(Double. amount))
                ;; trading-dates (mapv #(first %) ticker-prices)
                ]
            (recur (+ cash (* (Double. amount) price))
                   (assoc portfolio ticker (- (get portfolio ticker 0) (Double. amount)))
                   (assoc portfolio-composition-by-date executed-date (assoc portfolio ticker (- (get portfolio ticker 0) (Double. amount))))
                   (merge-with + portfolio-value (zipmap (map first ticker-prices) 
                                                         (map #(- (* (Double. amount) price) %) (map * prices amounts)))) ;; PnL for each trading day relative to trade date (short) = Market value of the holdings on the trade date - Market value of each holding for trading days after the trade date 
                   (- current-value (* (Double. amount) currPrice))
                   
                  ;;  (assoc stock-performance ticker (calculate-returns-with-corresponding-date prices trading-dates))
                   (assoc cash-invested ticker (- (get cash-invested ticker 0) (* (Double. amount) price)))
                   (assoc cash-invested-by-date executed-date (assoc cash-invested ticker (- (get cash-invested ticker 0) (* (Double. amount) price)))) 
                   ;; Be careful of signage, sell orders should "increase" cash 
                   (assoc change-in-cash-by-date executed-date  
                          (if (empty? change-in-cash-by-date)
                          
                            ;; If this is the first trade, just put in the initial investment
                            (+ 0 (* (Double. amount) price))

                            ;; Add new trade notional to most recent cash change
                            (+ (get change-in-cash-by-date 
                            ;; Get most recent trade date 
                                    (.toString 
                                     (reduce #(if (> (.compareTo %1 %2) 0) %1 %2) ;; .compareTo returns a positive integer if %1 is greater than %0, zero if they are equal, otherwise negative integer  
                                             (map date-parser 
                                                  (keys change-in-cash-by-date)))) 0
                                  ) (* (Double. amount) price)
                              ) 
                          ))
                   (if (= (get complete-stock-prices ticker "") "") ;; Check if we have to store new stock prices into map 
                     (assoc complete-stock-prices ticker ticker-prices)
                     complete-stock-prices) 
                   (rest data))) ;; Remove the first row
          )))))