;; gorilla-repl.fileformat = 1

;; **
;;; # CIM Portfolio
;; **

;; **
;;; ### Required packages
;; **

;; @@
(ns cim_portfolio.portfolio
  (:require [clojure.data.csv :as csv]
            [clj-http.client :as http]
            [cheshire.core :as json]
            [clj-time.core :as t]
            [clj-time.format :as tf]
            [clojure.string :as str]
            [java-time :as jt]
            [cim_portfolio.server :as server]
            ))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-nil'>nil</span>","value":"nil"}
;; <=

;; **
;;; ### Helper Functions
;; **

;; @@
;; FOR DATE PROCESSING
(def multi-parser (tf/formatter (t/default-time-zone) "YYYY-MM-dd" "YYYY/MM/dd" "YYYYMMdd"))

(defn parse-date [date]
  (tf/unparse multi-parser (tf/parse multi-parser date)))

(defn read-csv [file]
  (with-open [reader (clojure.java.io/reader file)]
    (doall (csv/read-csv reader))))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/read-csv</span>","value":"#'cim_portfolio.portfolio/read-csv"}
;; <=

;; @@
(parse-date "2023/12/25")
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-string'>&quot;2023-12-25&quot;</span>","value":"\"2023-12-25\""}
;; <=

;; @@
;; HELPER FUNCTIONS FOR ORDERING A MAP BY THE DATE
(defn jt-parse-date [date-str]
  (jt/local-date "yyyy-MM-dd" date-str))

(defn jt-compare-dates [date-str1 date-str2]
  (let [date1 (jt-parse-date date-str1)
        date2 (jt-parse-date date-str2)]
    (jt/before? date1 date2)))

(defn sort-map-by-date [map]
  (into (sorted-map-by jt-compare-dates) map))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/sort-map-by-date</span>","value":"#'cim_portfolio.portfolio/sort-map-by-date"}
;; <=

;; @@
;; Helper functions for computing cumulative returns
(defn sum-up-to-key [key data]
  (
   + (get data key 0)		;; Adds data entry of key itself as well
     (->> (keys data)	;; calculates the sum of entries till key
       (take-while #(not= % key))
       (map #(get data % 0))
       (apply +))
   )
  
)


(sum-up-to-key "c" {"a" 1 "b" 2 "c" 3 "d" 4 "e" 5}) ; Output: 6
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-long'>6</span>","value":"6"}
;; <=

;; @@
;; Computes arithmetic, log, and cumulative return for a given list of prices
(defn calculate-returns [prices]
  (let [price-changes (map #(double (/ (second %) (first %))) (partition 2 1 prices))
        arithmetic-returns (mapv #(- % 1.0) price-changes)
        log-returns (mapv #(Math/log %) price-changes)
        cumulative-log-return (reduce + log-returns)]
    {
     :cumulative-return cumulative-log-return
     :arithmetic-returns arithmetic-returns
     :log-returns log-returns
     }))

;; Similar to function above - associates the returns with their corresponding date
(defn calculate-returns-with-corresponding-date [prices dates]
  (let [price-changes (map #(double (/ (second %) (first %))) (partition 2 1 prices))
        arithmetic-returns (mapv #(- % 1.0) price-changes)
        log-returns (mapv #(Math/log %) price-changes)
        cumulative-log-return (reduce + log-returns)]
    {
     :cumulative-return cumulative-log-return
     :arithmetic-returns (sort-map-by-date (zipmap (rest dates) arithmetic-returns))
     :log-returns (sort-map-by-date (zipmap (rest dates) log-returns))
     }))

;; Calculates portfolio return - accepts map {:stock cash-invested} and stock-performance generated by calculate-returns
(defn calculate-portfolio-return [cash-invested returns]
  (let [total-investment (apply + (vals cash-invested))]
    (->> cash-invested
         (map (fn [[security invested]]
                (let [weight (/ invested total-investment)
                      return (:cumulative-return (get returns security))]
                  (* weight return))))
         (apply +))))

;; Calculates cumulative return UP TILL a given date
(defn get-cumulative-return-till-given-date [cumulative-returns date]
  (sum-up-to-key date cumulative-returns)
)

;; Only calculates portfolio return up till a given date
(defn calculate-portfolio-return-for-given-date [cash-invested returns date]
  ;(println "------")
  ;(println "Calculating returns on: " date)
  ;(println cash-invested)
  ;(println "------")
  (let [total-investment (apply + (vals cash-invested))]
    (->> cash-invested
         (map (fn [[security invested]]
                (let [weight (/ invested total-investment)
                      return (get-cumulative-return-till-given-date (:log-returns (get returns security)) date)
                     ]
                  (* weight return))))
         (apply +))))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/calculate-portfolio-return-for-given-date</span>","value":"#'cim_portfolio.portfolio/calculate-portfolio-return-for-given-date"}
;; <=

;; @@
(calculate-returns [100 110 120 130])
;; @@
;; =>
;;; {"type":"list-like","open":"<span class='clj-map'>{</span>","close":"<span class='clj-map'>}</span>","separator":", ","items":[{"type":"list-like","open":"","close":"","separator":" ","items":[{"type":"html","content":"<span class='clj-keyword'>:cumulative-return</span>","value":":cumulative-return"},{"type":"html","content":"<span class='clj-double'>0.262364264467491</span>","value":"0.262364264467491"}],"value":"[:cumulative-return 0.262364264467491]"},{"type":"list-like","open":"","close":"","separator":" ","items":[{"type":"html","content":"<span class='clj-keyword'>:arithmetic-returns</span>","value":":arithmetic-returns"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-double'>0.10000000000000009</span>","value":"0.10000000000000009"},{"type":"html","content":"<span class='clj-double'>0.09090909090909105</span>","value":"0.09090909090909105"},{"type":"html","content":"<span class='clj-double'>0.08333333333333304</span>","value":"0.08333333333333304"}],"value":"[0.10000000000000009 0.09090909090909105 0.08333333333333304]"}],"value":"[:arithmetic-returns [0.10000000000000009 0.09090909090909105 0.08333333333333304]]"},{"type":"list-like","open":"","close":"","separator":" ","items":[{"type":"html","content":"<span class='clj-keyword'>:log-returns</span>","value":":log-returns"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-double'>0.09531017980432493</span>","value":"0.09531017980432493"},{"type":"html","content":"<span class='clj-double'>0.0870113769896299</span>","value":"0.0870113769896299"},{"type":"html","content":"<span class='clj-double'>0.08004270767353615</span>","value":"0.08004270767353615"}],"value":"[0.09531017980432493 0.0870113769896299 0.08004270767353615]"}],"value":"[:log-returns [0.09531017980432493 0.0870113769896299 0.08004270767353615]]"}],"value":"{:cumulative-return 0.262364264467491, :arithmetic-returns [0.10000000000000009 0.09090909090909105 0.08333333333333304], :log-returns [0.09531017980432493 0.0870113769896299 0.08004270767353615]}"}
;; <=

;; **
;;; ### YFinance API
;; **

;; @@
(server/get-ticker-price-all "NVDA" "2024-02-15")
;; @@
;; ->
;;; [*********************100%%**********************]  1 of 1 completed
;;; 
;; <-
;; =>
;;; {"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-16&quot;</span>","value":"\"2024-02-16\""},{"type":"html","content":"<span class='clj-double'>741.0</span>","value":"741.0"},{"type":"html","content":"<span class='clj-double'>726.0959472656</span>","value":"726.0959472656"}],"value":"[\"2024-02-16\" 741.0 726.0959472656]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-20&quot;</span>","value":"\"2024-02-20\""},{"type":"html","content":"<span class='clj-double'>719.4699707031</span>","value":"719.4699707031"},{"type":"html","content":"<span class='clj-double'>694.4874267578</span>","value":"694.4874267578"}],"value":"[\"2024-02-20\" 719.4699707031 694.4874267578]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-21&quot;</span>","value":"\"2024-02-21\""},{"type":"html","content":"<span class='clj-double'>680.0599975586</span>","value":"680.0599975586"},{"type":"html","content":"<span class='clj-double'>674.688293457</span>","value":"674.688293457"}],"value":"[\"2024-02-21\" 680.0599975586 674.688293457]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-22&quot;</span>","value":"\"2024-02-22\""},{"type":"html","content":"<span class='clj-double'>750.25</span>","value":"750.25"},{"type":"html","content":"<span class='clj-double'>785.3431396484</span>","value":"785.3431396484"}],"value":"[\"2024-02-22\" 750.25 785.3431396484]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-23&quot;</span>","value":"\"2024-02-23\""},{"type":"html","content":"<span class='clj-double'>807.9000244141</span>","value":"807.9000244141"},{"type":"html","content":"<span class='clj-double'>788.1329956055</span>","value":"788.1329956055"}],"value":"[\"2024-02-23\" 807.9000244141 788.1329956055]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-26&quot;</span>","value":"\"2024-02-26\""},{"type":"html","content":"<span class='clj-double'>797.0</span>","value":"797.0"},{"type":"html","content":"<span class='clj-double'>790.8828735352</span>","value":"790.8828735352"}],"value":"[\"2024-02-26\" 797.0 790.8828735352]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-27&quot;</span>","value":"\"2024-02-27\""},{"type":"html","content":"<span class='clj-double'>793.8099975586</span>","value":"793.8099975586"},{"type":"html","content":"<span class='clj-double'>786.9730834961</span>","value":"786.9730834961"}],"value":"[\"2024-02-27\" 793.8099975586 786.9730834961]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-28&quot;</span>","value":"\"2024-02-28\""},{"type":"html","content":"<span class='clj-double'>776.200012207</span>","value":"776.200012207"},{"type":"html","content":"<span class='clj-double'>776.5935668945</span>","value":"776.5935668945"}],"value":"[\"2024-02-28\" 776.200012207 776.5935668945]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-02-29&quot;</span>","value":"\"2024-02-29\""},{"type":"html","content":"<span class='clj-double'>790.9400024414</span>","value":"790.9400024414"},{"type":"html","content":"<span class='clj-double'>791.0828857422</span>","value":"791.0828857422"}],"value":"[\"2024-02-29\" 790.9400024414 791.0828857422]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-01&quot;</span>","value":"\"2024-03-01\""},{"type":"html","content":"<span class='clj-double'>800.0</span>","value":"800.0"},{"type":"html","content":"<span class='clj-double'>822.7514038086</span>","value":"822.7514038086"}],"value":"[\"2024-03-01\" 800.0 822.7514038086]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-04&quot;</span>","value":"\"2024-03-04\""},{"type":"html","content":"<span class='clj-double'>841.299987793</span>","value":"841.299987793"},{"type":"html","content":"<span class='clj-double'>852.3300170898</span>","value":"852.3300170898"}],"value":"[\"2024-03-04\" 841.299987793 852.3300170898]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-05&quot;</span>","value":"\"2024-03-05\""},{"type":"html","content":"<span class='clj-double'>852.700012207</span>","value":"852.700012207"},{"type":"html","content":"<span class='clj-double'>859.6400146484</span>","value":"859.6400146484"}],"value":"[\"2024-03-05\" 852.700012207 859.6400146484]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-06&quot;</span>","value":"\"2024-03-06\""},{"type":"html","content":"<span class='clj-double'>880.2199707031</span>","value":"880.2199707031"},{"type":"html","content":"<span class='clj-double'>887.0</span>","value":"887.0"}],"value":"[\"2024-03-06\" 880.2199707031 887.0]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-07&quot;</span>","value":"\"2024-03-07\""},{"type":"html","content":"<span class='clj-double'>901.5800170898</span>","value":"901.5800170898"},{"type":"html","content":"<span class='clj-double'>926.6900024414</span>","value":"926.6900024414"}],"value":"[\"2024-03-07\" 901.5800170898 926.6900024414]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-08&quot;</span>","value":"\"2024-03-08\""},{"type":"html","content":"<span class='clj-double'>951.3800048828</span>","value":"951.3800048828"},{"type":"html","content":"<span class='clj-double'>875.2800292969</span>","value":"875.2800292969"}],"value":"[\"2024-03-08\" 951.3800048828 875.2800292969]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-11&quot;</span>","value":"\"2024-03-11\""},{"type":"html","content":"<span class='clj-double'>864.2899780273</span>","value":"864.2899780273"},{"type":"html","content":"<span class='clj-double'>857.7399902344</span>","value":"857.7399902344"}],"value":"[\"2024-03-11\" 864.2899780273 857.7399902344]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-12&quot;</span>","value":"\"2024-03-12\""},{"type":"html","content":"<span class='clj-double'>880.4899902344</span>","value":"880.4899902344"},{"type":"html","content":"<span class='clj-double'>919.1300048828</span>","value":"919.1300048828"}],"value":"[\"2024-03-12\" 880.4899902344 919.1300048828]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-13&quot;</span>","value":"\"2024-03-13\""},{"type":"html","content":"<span class='clj-double'>910.549987793</span>","value":"910.549987793"},{"type":"html","content":"<span class='clj-double'>908.8800048828</span>","value":"908.8800048828"}],"value":"[\"2024-03-13\" 910.549987793 908.8800048828]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-14&quot;</span>","value":"\"2024-03-14\""},{"type":"html","content":"<span class='clj-double'>895.7700195312</span>","value":"895.7700195312"},{"type":"html","content":"<span class='clj-double'>879.4400024414</span>","value":"879.4400024414"}],"value":"[\"2024-03-14\" 895.7700195312 879.4400024414]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-15&quot;</span>","value":"\"2024-03-15\""},{"type":"html","content":"<span class='clj-double'>869.299987793</span>","value":"869.299987793"},{"type":"html","content":"<span class='clj-double'>878.3699951172</span>","value":"878.3699951172"}],"value":"[\"2024-03-15\" 869.299987793 878.3699951172]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-18&quot;</span>","value":"\"2024-03-18\""},{"type":"html","content":"<span class='clj-double'>903.8800048828</span>","value":"903.8800048828"},{"type":"html","content":"<span class='clj-double'>884.549987793</span>","value":"884.549987793"}],"value":"[\"2024-03-18\" 903.8800048828 884.549987793]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-19&quot;</span>","value":"\"2024-03-19\""},{"type":"html","content":"<span class='clj-double'>867.0</span>","value":"867.0"},{"type":"html","content":"<span class='clj-double'>893.9799804688</span>","value":"893.9799804688"}],"value":"[\"2024-03-19\" 867.0 893.9799804688]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-20&quot;</span>","value":"\"2024-03-20\""},{"type":"html","content":"<span class='clj-double'>897.9699707031</span>","value":"897.9699707031"},{"type":"html","content":"<span class='clj-double'>903.7199707031</span>","value":"903.7199707031"}],"value":"[\"2024-03-20\" 897.9699707031 903.7199707031]"},{"type":"list-like","open":"<span class='clj-vector'>[</span>","close":"<span class='clj-vector'>]</span>","separator":" ","items":[{"type":"html","content":"<span class='clj-string'>&quot;2024-03-21&quot;</span>","value":"\"2024-03-21\""},{"type":"html","content":"<span class='clj-double'>923.0</span>","value":"923.0"},{"type":"html","content":"<span class='clj-double'>914.3499755859</span>","value":"914.3499755859"}],"value":"[\"2024-03-21\" 923.0 914.3499755859]"}],"value":"[[\"2024-02-16\" 741.0 726.0959472656] [\"2024-02-20\" 719.4699707031 694.4874267578] [\"2024-02-21\" 680.0599975586 674.688293457] [\"2024-02-22\" 750.25 785.3431396484] [\"2024-02-23\" 807.9000244141 788.1329956055] [\"2024-02-26\" 797.0 790.8828735352] [\"2024-02-27\" 793.8099975586 786.9730834961] [\"2024-02-28\" 776.200012207 776.5935668945] [\"2024-02-29\" 790.9400024414 791.0828857422] [\"2024-03-01\" 800.0 822.7514038086] [\"2024-03-04\" 841.299987793 852.3300170898] [\"2024-03-05\" 852.700012207 859.6400146484] [\"2024-03-06\" 880.2199707031 887.0] [\"2024-03-07\" 901.5800170898 926.6900024414] [\"2024-03-08\" 951.3800048828 875.2800292969] [\"2024-03-11\" 864.2899780273 857.7399902344] [\"2024-03-12\" 880.4899902344 919.1300048828] [\"2024-03-13\" 910.549987793 908.8800048828] [\"2024-03-14\" 895.7700195312 879.4400024414] [\"2024-03-15\" 869.299987793 878.3699951172] [\"2024-03-18\" 903.8800048828 884.549987793] [\"2024-03-19\" 867.0 893.9799804688] [\"2024-03-20\" 897.9699707031 903.7199707031] [\"2024-03-21\" 923.0 914.3499755859]]"}
;; <=

;; **
;;; ### Portfolio Processing Section
;; **

;; @@
(defn calculate-portfolio-new [data]
  (loop [cash 0.0
         portfolio {}
         portfolio-value {}
         current-value 0.0
         stock-performance {}
         cash-invested {}
         cash-invested-by-date {}
         data (rest data)]
    (if (empty? data)
      [cash portfolio portfolio-value current-value cash-invested cash-invested-by-date stock-performance]
      (let [[date action amount ticker] (first data)
            ticker-prices (server/get-ticker-price-all ticker (parse-date date))
            executed-date (first (first ticker-prices))				; gets the date the buy/sell order is executed
            ]
        (cond
          (= action "buy")
          (if (pos? (Double. amount))
            (let [price (second (first ticker-prices))        	; Gets open price of next trading day
                  currPrice (nth (last ticker-prices) 2)		; Gets adj close price of latest day
                  prices (mapv #(nth % 2) ticker-prices)       	; Extracts the prices from ticker-prices
                  amounts (repeatedly (count prices) #(Double. amount))	; Creates a sequence of amounts matching the number of prices
                  trading-dates (mapv #(first %) ticker-prices)
                  ]
              (recur (- cash (* (Double. amount) price))
                     (assoc portfolio ticker (+ (get portfolio ticker 0) (Double. amount)))
                     (merge-with + portfolio-value (zipmap (map first ticker-prices) (map #(- % (* (Double. amount) price))(map * prices amounts)))) ; Updates portfolio-value with the calculated values
                     (+ current-value (* (Double. amount) currPrice))
                     
                     (assoc stock-performance ticker (calculate-returns-with-corresponding-date prices trading-dates))
                     (assoc cash-invested ticker (+ (get cash-invested ticker 0) (* (Double. amount) price)))
                     (assoc cash-invested-by-date executed-date (assoc cash-invested ticker (+ (get cash-invested ticker 0) (* (Double. amount) price))))
                     (rest data)))
            (recur cash portfolio portfolio-value current-value cash-invested cash-invested-by-date stock-performance (rest data)))

          (= action "sell")
          (let [price (second (first ticker-prices))
                currPrice (second (last ticker-prices))
                prices (map second ticker-prices)
                amounts (repeatedly (count prices) #(Double. amount))
                trading-dates (mapv #(first %) ticker-prices)
                ]
            (recur (+ cash (* (Double. amount) price))
                   (assoc portfolio ticker (- (get portfolio ticker 0) (Double. amount)))
                   (merge-with + portfolio-value (zipmap (map first ticker-prices) (map #(- % (* (Double. amount) price))(map * prices amounts)))) ; Updates portfolio-value with the calculated values
                   (- current-value (* (Double. amount) currPrice))
                   
                   (assoc stock-performance ticker (calculate-returns-with-corresponding-date prices trading-dates))
                   (assoc cash-invested ticker (- (get cash-invested ticker 0) (* (Double. amount) price)))
                   (assoc cash-invested-by-date executed-date (assoc cash-invested ticker (- (get cash-invested ticker 0) (* (Double. amount) price))))
                   (rest data)))
          )))))
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/calculate-portfolio-new</span>","value":"#'cim_portfolio.portfolio/calculate-portfolio-new"}
;; <=

;; @@
(def portfolio-options {
                        :starting-cash 0
                       }
)

(def view-options {
                   :show-individual-stock-performance-by-day 	true
                   :show-cumulative-portfolio-return-by-day		true
                   :show-portfolio-value-by-day					true
                  }
)
;; @@
;; =>
;;; {"type":"html","content":"<span class='clj-var'>#&#x27;cim_portfolio.portfolio/view-options</span>","value":"#'cim_portfolio.portfolio/view-options"}
;; <=

;; @@
(def input-file "examples/testPortfolio1.csv")

(let [data (read-csv input-file)
      [cash portfolio portfolio-value current-value cash-invested cash-invested-by-date stock-performance] (calculate-portfolio-new data)
      sorted-portfolio-value (map #(vector (first %) (+ (:starting-cash portfolio-options) (second %))) (sort-map-by-date portfolio-value))
      cash-invested-by-dates (into [] cash-invested-by-date)
      returns-by-date (zipmap (map #(first %) cash-invested-by-date)(mapv #(calculate-portfolio-return-for-given-date (second %) stock-performance (first %)) cash-invested-by-dates))
      ]
  
  (println "\n\n----------------------------------")
  (println "Current Portfolio Value:" (+ (:starting-cash portfolio-options) (+ cash current-value)) "\n")
  (println "Cash On Hand (excluding value of portfolio):" (+ (:starting-cash portfolio-options) cash) "\n")
  (println "Portfolio (units held of each stock):" portfolio "\n")
  (println "Cash invested in each stock: " cash-invested "\n")
  (println "Cumulative Portfolio Return: " (calculate-portfolio-return cash-invested stock-performance) "\n")
  
  (println "----------------------------------")
  (if (:show-cumulative-portfolio-return-by-day view-options) (println "Portfolio Return by date: \n" returns-by-date))
  (println "----------------------------------\n")
  
  (println "----------------------------------")
  (println "Cumulative Portfolio Value: ")
  (if (:show-portfolio-value-by-day view-options) 
    (run! println sorted-portfolio-value)
    (println "Omitting...")
  )
  (println "----------------------------------\n")
  
  (println "----------------------------------")
  (println "Individual Stock Performance: ")
  (if (:show-individual-stock-performance-by-day view-options) 
    (run! println stock-performance)
    (println "Omitting...")
  )
  (println "----------------------------------\n")
)
;; @@
;; ->
;;; [*********************100%%**********************]  1 of 1 completed
;;; [*********************100%%**********************]  1 of 1 completed
;;; [*********************100%%**********************]  1 of 1 completed
;;; [*********************100%%**********************]  1 of 1 completed
;;; 
;;; 
;;; ----------------------------------
;;; Current Portfolio Value: 16562.097473146 
;;; 
;;; Cash On Hand (excluding value of portfolio): -49328.20037841599 
;;; 
;;; Portfolio (units held of each stock): {NVDA 70.0, GOOG 50.0, TSLA -30.0} 
;;; 
;;; Cash invested in each stock:  {NVDA 48171.300659181, GOOG 7172.49984741, TSLA -6015.600128175} 
;;; 
;;; Cumulative Portfolio Return:  0.08992496555730593 
;;; 
;;; ----------------------------------
;;; Portfolio Return by date: 
;;;  {2024-02-16 0.06572089929071964, 2024-02-26 0.0660567176615914, 2024-03-01 0.07449814792581735, 2024-03-11 0.08066622143392585}
;;; ----------------------------------
;;; 
;;; ----------------------------------
;;; Cumulative Portfolio Value: 
;;; [2024-02-16 -1490.405273440003]
;;; [2024-02-20 -4651.2573242200015]
;;; [2024-02-21 -6631.170654300004]
;;; [2024-02-22 4434.313964839996]
;;; [2024-02-23 4713.299560550004]
;;; [2024-02-26 4753.287506110005]
;;; [2024-02-27 4429.8088073750005]
;;; [2024-02-28 3258.3564758299963]
;;; [2024-02-29 4824.788665775001]
;;; [2024-03-01 7906.640625005]
;;; [2024-03-04 10616.801452629996]
;;; [2024-03-05 10856.401519773997]
;;; [2024-03-06 13439.600067141]
;;; [2024-03-07 17373.40072632]
;;; [2024-03-08 12499.402618410004]
;;; [2024-03-11 10696.399078371003]
;;; [2024-03-12 17425.000762943]
;;; [2024-03-13 17217.701110845]
;;; [2024-03-14 13850.401458742002]
;;; [2024-03-15 12702.499847414005]
;;; [2024-03-18 14879.199523930005]
;;; [2024-03-19 14757.998657233007]
;;; [2024-03-20 16768.296508789]
;;; [2024-03-21 18636.898498533996]
;;; ----------------------------------
;;; 
;;; ----------------------------------
;;; Individual Stock Performance: 
;;; [NVDA {:cumulative-return 0.06572089929071964, :arithmetic-returns {2024-03-12 0.018743723309248228, 2024-03-13 0.03414007869708735, 2024-03-14 -0.016231913085435146, 2024-03-15 -0.029550030879636924, 2024-03-18 0.039779152853312016, 2024-03-19 -0.04080188153689934, 2024-03-20 0.03572084279480969, 2024-03-21 0.027874015962139342}, :log-returns {2024-03-12 0.01857022438511924, 2024-03-13 0.03357023953839369, 2024-03-14 -0.01636509373764299, 2024-03-15 -0.029995429355316856, 2024-03-18 0.039008337577523575, 2024-03-19 -0.04165763683966735, 2024-03-20 0.035097650765528586, 2024-03-21 0.027492606956781733}}]
;;; [GOOG {:cumulative-return 0.0695260995801679, :arithmetic-returns {2024-02-27 0.00972977371891881, 2024-02-28 -0.019057910859243576, 2024-02-29 0.01709965967213356, 2024-03-01 -0.012161947081457236, 2024-03-04 -0.028099687365633286, 2024-03-05 -0.003129643654627867, 2024-03-06 -0.009119459050920375, 2024-03-07 0.02021732033764745, 2024-03-08 0.007763884577428604, 2024-03-11 0.01944390113613914, 2024-03-12 0.0048941461339531145, 2024-03-13 0.008236708175892948, 2024-03-14 0.025360460020227737, 2024-03-15 -0.015033935319771152, 2024-03-18 0.04438346795998149, 2024-03-19 -0.0037715353900450443, 2024-03-20 0.01189828642973878, 2024-03-21 -0.006279978812104736}, :log-returns {2024-02-27 0.009682744281726864, 2024-02-28 -0.01924185363555232, 2024-02-29 0.016955106043255397, 2024-03-01 -0.012236508719703257, 2024-03-04 -0.028502038799374928, 2024-03-05 -0.003134551231316087, 2024-03-06 -0.009161295864592816, 2024-03-07 0.020015663756857732, 2024-03-08 0.007733900719707719, 2024-03-11 0.01925728365879598, 2024-03-12 0.004882208733839472, 2024-03-13 0.008202971620612674, 2024-03-14 0.025044219081981015, 2024-03-15 -0.015148090504825953, 2024-03-18 0.043426728495015436, 2024-03-19 -0.0037786655630901826, 2024-03-20 0.011828058333563249, 2024-03-21 -0.006299780826732111}}]
;;; [TSLA {:cumulative-return -0.12821656453953195, :arithmetic-returns {2024-03-04 -0.008926832769100779, 2024-03-05 -0.0789009863272001, 2024-03-06 -0.016716730442960293, 2024-03-07 -0.03133506982371348, 2024-03-08 0.041009427279603994, 2024-03-11 -0.03333335014765837, 2024-03-12 0.01322318247166998, 2024-03-13 -0.026551167841931345, 2024-03-14 -0.0305114052943386, 2024-03-15 -0.02747809794957279, 2024-03-18 0.04204462157654065, 2024-03-19 0.013763064810594638, 2024-03-20 0.003713154950878872, 2024-03-21 0.019595372194219696}, :log-returns {2024-03-04 -0.008966915661229745, 2024-03-05 -0.08218774180298156, 2024-03-06 -0.016858031927332002, 2024-03-07 -0.03183651618203155, 2024-03-08 0.040190845576076405, 2024-03-11 -0.033901569069810844, 2024-03-12 0.013136519333363105, 2024-03-13 -0.026910016251739145, 2024-03-14 -0.030986568467997484, 2024-03-15 -0.02786268235452426, 2024-03-18 0.041184765424412045, 2024-03-19 0.013669213970453118, 2024-03-20 0.003706278208716729, 2024-03-21 0.01940585466509325}}]
;;; ----------------------------------
;;; 
;;; 
;; <-
;; =>
;;; {"type":"html","content":"<span class='clj-nil'>nil</span>","value":"nil"}
;; <=

;; **
;;; 
;; **

;; @@

;; @@
